## Incident Management Data

In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('../../data/raw/incident_event_log.csv')
df.shape

(141712, 36)

In [4]:
df.columns

Index(['number', 'incident_state', 'active', 'reassignment_count',
       'reopen_count', 'sys_mod_count', 'made_sla', 'caller_id', 'opened_by',
       'opened_at', 'sys_created_by', 'sys_created_at', 'sys_updated_by',
       'sys_updated_at', 'contact_type', 'location', 'category', 'subcategory',
       'u_symptom', 'cmdb_ci', 'impact', 'urgency', 'priority',
       'assignment_group', 'assigned_to', 'knowledge',
       'u_priority_confirmation', 'notify', 'problem_id', 'rfc', 'vendor',
       'caused_by', 'closed_code', 'resolved_by', 'resolved_at', 'closed_at'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 141712 entries, 0 to 141711
Data columns (total 36 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   number                   141712 non-null  str
 1   incident_state           141712 non-null  str
 2   active                   141712 non-null  bool
 3   reassignment_count       141712 non-null  int64
 4   reopen_count             141712 non-null  int64
 5   sys_mod_count            141712 non-null  int64
 6   made_sla                 141712 non-null  bool
 7   caller_id                141712 non-null  str
 8   opened_by                141712 non-null  str
 9   opened_at                141712 non-null  str
 10  sys_created_by           141712 non-null  str
 11  sys_created_at           141712 non-null  str
 12  sys_updated_by           141712 non-null  str
 13  sys_updated_at           141712 non-null  str
 14  contact_type             141712 non-null  str
 15  location                 141712 non-null  str
 16  category                 141712 non-null  str
 17  subcategory              141712 non-null  str
 18  u_symptom                141712 non-null  str
 19  cmdb_ci                  141712 non-null  str
 20  impact                   141712 non-null  str
 21  urgency                  141712 non-null  str
 22  priority                 141712 non-null  str
 23  assignment_group         141712 non-null  str
 24  assigned_to              141712 non-null  str
 25  knowledge                141712 non-null  bool
 26  u_priority_confirmation  141712 non-null  bool
 27  notify                   141712 non-null  str
 28  problem_id               141712 non-null  str
 29  rfc                      141712 non-null  str
 30  vendor                   141712 non-null  str
 31  caused_by                141712 non-null  str
 32  closed_code              141712 non-null  str
 33  resolved_by              141712 non-null  str
 34  resolved_at              141712 non-null  str
 35  closed_at                141712 non-null  str
dtypes: bool(4), int64(3), str(29)
memory usage: 35.1 MB

In [6]:
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00

In [7]:
df.isnull().sum()

number                     0
incident_state             0
active                     0
reassignment_count         0
reopen_count               0
sys_mod_count              0
made_sla                   0
caller_id                  0
opened_by                  0
opened_at                  0
sys_created_by             0
sys_created_at             0
sys_updated_by             0
sys_updated_at             0
contact_type               0
location                   0
category                   0
subcategory                0
u_symptom                  0
cmdb_ci                    0
impact                     0
urgency                    0
priority                   0
assignment_group           0
assigned_to                0
knowledge                  0
u_priority_confirmation    0
notify                     0
problem_id                 0
rfc                        0
vendor                     0
caused_by                  0
closed_code                0
resolved_by                0
resolved_at                0
closed_at                  0
dtype: int64

In [8]:
df.describe()

       reassignment_count   reopen_count  sys_mod_count
count       141712.000000  141712.000000  141712.000000
mean             1.104197       0.021918       5.080946
std              1.734673       0.207302       7.680652
min              0.000000       0.000000       0.000000
25%              0.000000       0.000000       1.000000
50%              1.000000       0.000000       3.000000
75%              1.000000       0.000000       6.000000
max             27.000000       8.000000     129.000000

In [9]:
df['number'].duplicated().value_counts()

number
True     116794
False     24918
Name: count, dtype: int64

In [10]:
(df=='?').sum()

number                          0
incident_state                  0
active                          0
reassignment_count              0
reopen_count                    0
sys_mod_count                   0
made_sla                        0
caller_id                      29
opened_by                    4835
opened_at                       0
sys_created_by              53076
sys_created_at              53076
sys_updated_by                  0
sys_updated_at                  0
contact_type                    0
location                       76
category                       78
subcategory                   111
u_symptom                   32964
cmdb_ci                    141267
impact                          0
urgency                         0
priority                        0
assignment_group            14213
assigned_to                 27496
knowledge                       0
u_priority_confirmation         0
notify                          0
problem_id                 139417
rfc                        140721
vendor                     141468
caused_by                  141689
closed_code                   714
resolved_by                   226
resolved_at                  3141
closed_at                       0
dtype: int64

In [11]:
df['priority'].duplicated().value_counts()

priority
True     141708
False         4
Name: count, dtype: int64

In [12]:
df['priority'].unique()

<StringArray>
['3 - Moderate', '2 - High', '4 - Low', '1 - Critical']
Length: 4, dtype: str

In [13]:
# df.groupby('priority').agg(total_incidents=('priority','size'))
print(df.groupby('priority').size())
print((df.groupby('priority').size()/len(df))*100)

priority
1 - Critical      2258
2 - High          2972
3 - Moderate    132452
4 - Low           4030
dtype: int64
priority
1 - Critical     1.593372
2 - High         2.097211
3 - Moderate    93.465620
4 - Low          2.843796
dtype: float64

In [14]:
df['impact'].unique()

<StringArray>
['2 - Medium', '1 - High', '3 - Low']
Length: 3, dtype: str

In [15]:
print(df.groupby('impact').size())
print((df.groupby('impact').size()/len(df))*100)

impact
1 - High        3491
2 - Medium    134335
3 - Low         3886
dtype: int64
impact
1 - High       2.463447
2 - Medium    94.794372
3 - Low        2.742181
dtype: float64

In [16]:
df['urgency'].unique()

<StringArray>
['2 - Medium', '3 - Low', '1 - High']
Length: 3, dtype: str

In [17]:
print(df.groupby('urgency').size())
print((df.groupby('urgency').size()/len(df))*100)

urgency
1 - High        4020
2 - Medium    134094
3 - Low         3598
dtype: int64
urgency
1 - High       2.836739
2 - Medium    94.624308
3 - Low        2.538952
dtype: float64

In [18]:
df.columns

Index(['number', 'incident_state', 'active', 'reassignment_count',
       'reopen_count', 'sys_mod_count', 'made_sla', 'caller_id', 'opened_by',
       'opened_at', 'sys_created_by', 'sys_created_at', 'sys_updated_by',
       'sys_updated_at', 'contact_type', 'location', 'category', 'subcategory',
       'u_symptom', 'cmdb_ci', 'impact', 'urgency', 'priority',
       'assignment_group', 'assigned_to', 'knowledge',
       'u_priority_confirmation', 'notify', 'problem_id', 'rfc', 'vendor',
       'caused_by', 'closed_code', 'resolved_by', 'resolved_at', 'closed_at'],
      dtype='str')

In [19]:
print(df['made_sla'].unique())

[ True False]

In [20]:
print(df.groupby('made_sla').size())
print()
print((df.groupby('made_sla').size()/len(df))*100)

made_sla
False      9215
True     132497
dtype: int64

made_sla
False     6.502625
True     93.497375
dtype: float64

In [21]:
print(df['reassignment_count'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]

In [22]:
print(df.groupby('reassignment_count').size())

reassignment_count
0     69876
1     37104
2     15097
3      8274
4      4614
5      2595
6      1447
7       985
8       574
9       365
10      285
11      174
12      108
13       61
14       45
15       21
16       13
17       16
18       13
19        8
20       16
21        3
22        9
23        2
24        1
25        1
26        2
27        3
dtype: int64

In [23]:
print((df.groupby('reassignment_count').size()/len(df))*100)

reassignment_count
0     49.308457
1     26.182680
2     10.653297
3      5.838602
4      3.255899
5      1.831179
6      1.021085
7      0.695072
8      0.405047
9      0.257565
10     0.201112
11     0.122784
12     0.076211
13     0.043045
14     0.031755
15     0.014819
16     0.009174
17     0.011291
18     0.009174
19     0.005645
20     0.011291
21     0.002117
22     0.006351
23     0.001411
24     0.000706
25     0.000706
26     0.001411
27     0.002117
dtype: float64

In [24]:
df['reopen_count'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
print(df.groupby('reopen_count').size())
print()
print((df.groupby('reopen_count').size()/len(df))*100)

reopen_count
0    139398
1      1918
2       190
3       107
4        48
5        24
6        18
7         5
8         4
dtype: int64

reopen_count
0    98.367111
1     1.353449
2     0.134075
3     0.075505
4     0.033872
5     0.016936
6     0.012702
7     0.003528
8     0.002823
dtype: float64

In [26]:
df['incident_state'].unique()

<StringArray>
[               'New',           'Resolved',             'Closed',
             'Active', 'Awaiting User Info',   'Awaiting Problem',
    'Awaiting Vendor',  'Awaiting Evidence',               '-100']
Length: 9, dtype: str

In [27]:
print(df.groupby('incident_state').size())
print()
print((df.groupby('incident_state').size()/len(df))*100)

incident_state
-100                      5
Active                38716
Awaiting Evidence        38
Awaiting Problem        461
Awaiting User Info    14642
Awaiting Vendor         707
Closed                24985
New                   36407
Resolved              25751
dtype: int64

incident_state
-100                   0.003528
Active                27.320199
Awaiting Evidence      0.026815
Awaiting Problem       0.325308
Awaiting User Info    10.332223
Awaiting Vendor        0.498899
Closed                17.630829
New                   25.690838
Resolved              18.171362
dtype: float64

In [28]:
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00

In [29]:
df.loc[df['number']=='INC0000047']

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
5,INC0000047,Active,True,1,0,1,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
6,INC0000047,Active,True,1,0,2,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
7,INC0000047,Active,True,1,0,3,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
8,INC0000047,Active,True,1,0,4,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
9,INC0000047,Active,True,1,0,5,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
10,INC0000047,Awaiting User Info,True,1,0,6,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
11,INC0000047,Resolved,True,1,0,7,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
12,INC0000047,Closed,False,1,0,8,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00

In [30]:
df['contact_type'].unique()

<StringArray>
['Phone', 'Email', 'Self service', 'Direct opening', 'IVR']
Length: 5, dtype: str

In [31]:
# df.groupby('contact_type').size().sort_values(ascending=False).head(10)
df['contact_type'].value_counts().head(10)

contact_type
Phone             140462
Self service         995
Email                220
IVR                   18
Direct opening        17
Name: count, dtype: int64

In [32]:
(df['contact_type']=='?').sum()

np.int64(0)

In [33]:
df['location'].unique()

<StringArray>
['Location 143', 'Location 165', 'Location 204',  'Location 93',
 'Location 108', 'Location 161',  'Location 46',  'Location 42',
 'Location 229',  'Location 98',
 ...
 'Location 116',  'Location 94', 'Location 217',  'Location 19',
 'Location 105',  'Location 50',   'Location 4', 'Location 106',
 'Location 202', 'Location 246']
Length: 225, dtype: str

In [34]:
df['location'].value_counts().head(10)

location
Location 204    31690
Location 161    22605
Location 143    19245
Location 108    12623
Location 93     11554
Location 51      8016
Location 188     2142
Location 179     1975
Location 43      1748
Location 111     1530
Name: count, dtype: int64

In [35]:
(df['location']=='?').sum()

np.int64(76)

In [36]:
df['category'].unique()

<StringArray>
['Category 55', 'Category 40', 'Category 20',  'Category 9', 'Category 53',
 'Category 44', 'Category 45', 'Category 42', 'Category 32',  'Category 8',
 'Category 24', 'Category 61', 'Category 37', 'Category 26', 'Category 23',
 'Category 62', 'Category 17', 'Category 13', 'Category 35',           '?',
 'Category 43', 'Category 34', 'Category 19', 'Category 46', 'Category 63',
 'Category 51', 'Category 22', 'Category 30', 'Category 31', 'Category 15',
 'Category 47',  'Category 7', 'Category 57', 'Category 25', 'Category 56',
 'Category 38', 'Category 49',  'Category 4', 'Category 28', 'Category 41',
 'Category 36', 'Category 54', 'Category 29',  'Category 3', 'Category 27',
 'Category 33', 'Category 58',  'Category 2', 'Category 21', 'Category 16',
 'Category 50', 'Category 59', 'Category 12', 'Category 52',  'Category 5',
  'Category 6', 'Category 10', 'Category 48', 'Category 14']
Length: 59, dtype: str

In [37]:
df['category'].value_counts().head(10)

category
Category 26    18453
Category 42    15977
Category 53    15968
Category 46    13324
Category 23     7779
Category 9      7365
Category 32     7273
Category 37     6584
Category 57     6532
Category 20     5506
Name: count, dtype: int64

In [38]:
(df['category']=='?').sum()

np.int64(78)

In [39]:
df['subcategory'].unique()

<StringArray>
['Subcategory 170', 'Subcategory 215', 'Subcategory 125',  'Subcategory 97',
 'Subcategory 168', 'Subcategory 229',  'Subcategory 94', 'Subcategory 185',
 'Subcategory 110', 'Subcategory 164',
 ...
 'Subcategory 126',  'Subcategory 37', 'Subcategory 295', 'Subcategory 152',
 'Subcategory 155', 'Subcategory 131',  'Subcategory 14',  'Subcategory 71',
  'Subcategory 24',  'Subcategory 22']
Length: 255, dtype: str

In [40]:
df['subcategory'].value_counts().head(10)

subcategory
Subcategory 174    35785
Subcategory 223    15598
Subcategory 175    10496
Subcategory 164     7880
Subcategory 9       4124
Subcategory 275     3643
Subcategory 135     3467
Subcategory 170     3349
Subcategory 36      2917
Subcategory 75      2113
Name: count, dtype: int64

In [41]:
(df['subcategory']=='?').sum()

np.int64(111)

In [42]:
df['u_symptom'].unique()

<StringArray>
[ 'Symptom 72', 'Symptom 471', 'Symptom 450', 'Symptom 232', 'Symptom 580',
 'Symptom 311',           '?', 'Symptom 470', 'Symptom 592', 'Symptom 530',
 ...
 'Symptom 570',  'Symptom 83', 'Symptom 179',  'Symptom 81',  'Symptom 73',
 'Symptom 447', 'Symptom 103', 'Symptom 204', 'Symptom 565', 'Symptom 302']
Length: 526, dtype: str

In [43]:
df['u_symptom'].value_counts().head(10)

u_symptom
Symptom 491    51985
?              32964
Symptom 534     5559
Symptom 387     2583
Symptom 4       2532
Symptom 116     2394
Symptom 532     2097
Symptom 571     1771
Symptom 494     1367
Symptom 296     1359
Name: count, dtype: int64

In [44]:
(df['u_symptom']=='?').sum()

np.int64(32964)

In [45]:
df['made_sla'].head(10)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: made_sla, dtype: bool

In [46]:
df[['number','made_sla']]

            number  made_sla
0       INC0000045      True
1       INC0000045      True
2       INC0000045      True
3       INC0000045      True
4       INC0000047      True
...            ...       ...
141707  INC0120835      True
141708  INC0121064      True
141709  INC0121064      True
141710  INC0121064      True
141711  INC0121064      True

[141712 rows x 2 columns]

In [47]:
(df['incident_state']=='New').sum()

np.int64(36407)

In [48]:
df['sys_mod_count'].count()

np.int64(141712)

In [49]:
(df['sys_mod_count']==0).sum()

np.int64(24913)

In [50]:
df.loc[df['number']=='INC0000045',['number','incident_state','sys_mod_count']]

       number incident_state  sys_mod_count
0  INC0000045            New              0
1  INC0000045       Resolved              2
2  INC0000045       Resolved              3
3  INC0000045         Closed              4

In [51]:
df.loc[df['sys_mod_count']==0,['number','sys_mod_count']].count()

number           24913
sys_mod_count    24913
dtype: int64