# EDA

In [1]:
import pandas as pd

In [2]:
eda_df=pd.read_csv('../../data/raw/incident_event_log.csv')

In [3]:
eda_df['category'].unique()

<StringArray>
['Category 55', 'Category 40', 'Category 20',  'Category 9', 'Category 53',
 'Category 44', 'Category 45', 'Category 42', 'Category 32',  'Category 8',
 'Category 24', 'Category 61', 'Category 37', 'Category 26', 'Category 23',
 'Category 62', 'Category 17', 'Category 13', 'Category 35',           '?',
 'Category 43', 'Category 34', 'Category 19', 'Category 46', 'Category 63',
 'Category 51', 'Category 22', 'Category 30', 'Category 31', 'Category 15',
 'Category 47',  'Category 7', 'Category 57', 'Category 25', 'Category 56',
 'Category 38', 'Category 49',  'Category 4', 'Category 28', 'Category 41',
 'Category 36', 'Category 54', 'Category 29',  'Category 3', 'Category 27',
 'Category 33', 'Category 58',  'Category 2', 'Category 21', 'Category 16',
 'Category 50', 'Category 59', 'Category 12', 'Category 52',  'Category 5',
  'Category 6', 'Category 10', 'Category 48', 'Category 14']
Length: 59, dtype: str

In [4]:
category_details = (
    eda_df.groupby('category')['made_sla']
    .agg(
        Total_incidents='count',
        Breaches=lambda x: (x == False).sum()
    )
    .reset_index()
)

category_details['Breach_percentage'] = (
    category_details['Breaches']
    / category_details['Total_incidents']
) * 100

category_details = category_details.sort_values(
    by='Breach_percentage',
    ascending=False
)

In [5]:
category_details
%store category_details

Stored 'category_details' (DataFrame)

In [6]:
eda_df.loc[eda_df['category']=='Category 6']

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
140629,INC0084790,New,True,0,0,0,True,Caller 2079,Opened by 223,8/11/2016 14:18,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 5,18/11/2016 04:49,23/11/2016 05:00
140630,INC0084790,New,True,0,0,4,True,Caller 2079,Opened by 223,8/11/2016 14:18,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 5,18/11/2016 04:49,23/11/2016 05:00
140631,INC0084790,Resolved,True,0,0,5,True,Caller 2079,Opened by 223,8/11/2016 14:18,...,True,Do Not Notify,?,?,?,?,code 6,Resolved by 5,18/11/2016 04:49,23/11/2016 05:00
140632,INC0084790,Closed,False,0,0,6,False,Caller 2079,Opened by 223,8/11/2016 14:18,...,True,Do Not Notify,?,?,?,?,code 6,Resolved by 5,18/11/2016 04:49,23/11/2016 05:00
141641,INC0118678,New,True,0,0,0,True,Caller 5304,Opened by 195,10/2/2017 02:15,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 94,10/2/2017 05:07,15/2/2017 05:10
141642,INC0118678,Resolved,True,0,0,1,True,Caller 5304,Opened by 195,10/2/2017 02:15,...,True,Do Not Notify,?,?,?,?,code 6,Resolved by 94,10/2/2017 05:07,15/2/2017 05:10
141643,INC0118678,Closed,False,0,0,2,True,Caller 5304,Opened by 195,10/2/2017 02:15,...,True,Do Not Notify,?,?,?,?,code 6,Resolved by 94,10/2/2017 05:07,15/2/2017 05:10

In [7]:
category_details.info()

<class 'pandas.DataFrame'>
Index: 59 entries, 52 to 44
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           59 non-null     str
 1   Total_incidents    59 non-null     int64
 2   Breaches           59 non-null     int64
 3   Breach_percentage  59 non-null     float64
dtypes: float64(1), int64(2), str(1)
memory usage: 2.3 KB

In [8]:
eda_df['subcategory'].unique()

<StringArray>
['Subcategory 170', 'Subcategory 215', 'Subcategory 125',  'Subcategory 97',
 'Subcategory 168', 'Subcategory 229',  'Subcategory 94', 'Subcategory 185',
 'Subcategory 110', 'Subcategory 164',
 ...
 'Subcategory 126',  'Subcategory 37', 'Subcategory 295', 'Subcategory 152',
 'Subcategory 155', 'Subcategory 131',  'Subcategory 14',  'Subcategory 71',
  'Subcategory 24',  'Subcategory 22']
Length: 255, dtype: str

In [9]:
subcategory_details=eda_df.groupby('subcategory')['made_sla'].agg(Total_incidents='count',Breaches=lambda x:(x==False).sum()).reset_index()

subcategory_details['Breach_percentage']=((subcategory_details['Breaches']/subcategory_details['Total_incidents'])*100).round(2)

subcategory_details.sort_values(by='Breaches',ascending=False)

         subcategory  Total_incidents  Breaches  Breach_percentage
74   Subcategory 174            35785      2007               5.61
121  Subcategory 223            15598       688               4.41
75   Subcategory 175            10496       649               6.18
63   Subcategory 164             7880       543               6.89
48   Subcategory 150             1659       244              14.71
..               ...              ...       ...                ...
235   Subcategory 77               34         0               0.00
237    Subcategory 8                2         0               0.00
240   Subcategory 83               17         0               0.00
251   Subcategory 95                3         0               0.00
253   Subcategory 97                4         0               0.00

[255 rows x 4 columns]

In [10]:
subcategory_details[subcategory_details['Total_incidents']>100]

         subcategory  Total_incidents  Breaches  Breach_percentage
0                  ?              111         3               2.70
3    Subcategory 101              104         6               5.77
5    Subcategory 103             1517        66               4.35
7    Subcategory 105              246        19               7.72
8    Subcategory 106              180        15               8.33
..               ...              ...       ...                ...
245   Subcategory 88              624        74              11.86
246   Subcategory 89              112         8               7.14
247    Subcategory 9             4124       220               5.33
248   Subcategory 90              178        16               8.99
250   Subcategory 94              720        74              10.28

[107 rows x 4 columns]

In [11]:
subcategory_details.sort_values(by='Breaches',ascending=False).head(10)

         subcategory  Total_incidents  Breaches  Breach_percentage
74   Subcategory 174            35785      2007               5.61
121  Subcategory 223            15598       688               4.41
75   Subcategory 175            10496       649               6.18
63   Subcategory 164             7880       543               6.89
48   Subcategory 150             1659       244              14.71
37   Subcategory 135             3467       223               6.43
247    Subcategory 9             4124       220               5.33
70   Subcategory 170             3349       217               6.48
203   Subcategory 36             2917       216               7.40
168  Subcategory 275             3643       205               5.63

In [12]:
subcategory_details[subcategory_details['Total_incidents']>=500].sort_values(by='Breach_percentage',ascending=False).shape

(42, 4)

In [13]:
subcategory_details[(subcategory_details['Total_incidents']>=500) & (subcategory_details['Breach_percentage']>=6.5)].sort_values(by='Breach_percentage',ascending=False).shape
%store subcategory_details

Stored 'subcategory_details' (DataFrame)

In [14]:
location_details=eda_df.groupby('location')['made_sla'].agg(Total_incidents='count',Breaches=lambda x:(~x).sum()).reset_index()
location_details['Breach_rate']=((location_details['Breaches']/location_details['Total_incidents'])*100).round(2)
location_details.sort_values(by='Breach_rate',ascending=False)

         location  Total_incidents  Breaches  Breach_rate
160   Location 31                2         1        50.00
182   Location 53                3         1        33.33
113  Location 211                3         1        33.33
108  Location 207                3         1        33.33
3    Location 101                4         1        25.00
..            ...              ...       ...          ...
212   Location 87               10         0         0.00
213   Location 89                3         0         0.00
219   Location 94                4         0         0.00
220   Location 95                4         0         0.00
223   Location 98               10         0         0.00

[225 rows x 4 columns]

In [15]:
location_details[location_details['Total_incidents']>=500].sort_values(by='Breach_rate',ascending=False)

         location  Total_incidents  Breaches  Breach_rate
171   Location 42              666        54         8.11
166   Location 38              556        43         7.73
12   Location 111             1530       116         7.58
105  Location 204            31690      2250         7.10
36   Location 135             1094        77         7.04
44   Location 143            19245      1351         7.02
185   Location 56              907        63         6.95
170   Location 41              630        43         6.83
221   Location 96             1203        82         6.82
184   Location 55             1467        99         6.75
180   Location 51             8016       539         6.72
172   Location 43             1748       117         6.69
37   Location 136              736        49         6.66
78   Location 179             1975       131         6.63
218   Location 93            11554       765         6.62
183   Location 54              910        59         6.48
175   Location 46             1251        77         6.16
167   Location 39              523        32         6.12
132  Location 229              693        42         6.06
8    Location 108            12623       715         5.66
60   Location 161            22605      1185         5.24
222   Location 97              622        31         4.98
28   Location 128              669        33         4.93
27   Location 125              729        32         4.39
88   Location 188             2142        32         1.49

In [16]:
location_details.sort_values(by='Breaches',ascending=False)

         location  Total_incidents  Breaches  Breach_rate
105  Location 204            31690      2250         7.10
44   Location 143            19245      1351         7.02
60   Location 161            22605      1185         5.24
218   Location 93            11554       765         6.62
8    Location 108            12623       715         5.66
..            ...              ...       ...          ...
212   Location 87               10         0         0.00
213   Location 89                3         0         0.00
219   Location 94                4         0         0.00
220   Location 95                4         0         0.00
223   Location 98               10         0         0.00

[225 rows x 4 columns]

In [17]:
eda_df.loc[eda_df['location']=='Location 31',['location','made_sla']]

          location  made_sla
99361  Location 31      True
99362  Location 31     False

In [18]:
%store location_details

Stored 'location_details' (DataFrame)

In [19]:
contact_details=eda_df.groupby('contact_type')['made_sla'].agg(Total_incidents='count',Breaches=lambda x:(~x).sum())
contact_details['Breach_rate']=((contact_details['Breaches']/contact_details['Total_incidents'])*100).round(2)
contact_details.sort_values(by='Breach_rate',ascending=False).reset_index()

     contact_type  Total_incidents  Breaches  Breach_rate
0           Email              220        39        17.73
1    Self service              995        70         7.04
2           Phone           140462      9106         6.48
3  Direct opening               17         0         0.00
4             IVR               18         0         0.00

In [20]:
contact_details.sort_values(by='Breaches',ascending=False)

                Total_incidents  Breaches  Breach_rate
contact_type
Phone                    140462      9106         6.48
Self service                995        70         7.04
Email                       220        39        17.73
Direct opening               17         0         0.00
IVR                          18         0         0.00

In [21]:
%store contact_details

Stored 'contact_details' (DataFrame)

In [22]:
u_symptom_details=eda_df.groupby('u_symptom')['made_sla'].agg(Total_incidents='count',Breaches=lambda x:(~x).sum())
u_symptom_details['Breach_rate']=((u_symptom_details['Breaches']/u_symptom_details['Total_incidents'])*100).round(2)
u_symptom_details.sort_values(by='Breach_rate',ascending=False).reset_index()

       u_symptom  Total_incidents  Breaches  Breach_rate
0     Symptom 95                3         1        33.33
1     Symptom 14                3         1        33.33
2     Symptom 25                6         2        33.33
3    Symptom 516                4         1        25.00
4    Symptom 555                4         1        25.00
..           ...              ...       ...          ...
521  Symptom 133                2         0         0.00
522   Symptom 96                7         0         0.00
523  Symptom 109                7         0         0.00
524   Symptom 98                8         0         0.00
525   Symptom 99               14         0         0.00

[526 rows x 4 columns]

In [23]:
u_symptom_details[u_symptom_details['Total_incidents']>=500].sort_values(by='Breach_rate',ascending=False).reset_index()

      u_symptom  Total_incidents  Breaches  Breach_rate
0   Symptom 208             1112       117        10.52
1   Symptom 120              930        84         9.03
2     Symptom 4             2532       225         8.89
3     Symptom 6              702        62         8.83
4   Symptom 458              849        71         8.36
5   Symptom 592              562        46         8.19
6   Symptom 102              880        72         8.18
7   Symptom 571             1771       144         8.13
8             ?            32964      2587         7.85
9   Symptom 470             1051        79         7.52
10  Symptom 119              547        41         7.50
11  Symptom 117              578        42         7.27
12  Symptom 387             2583       163         6.31
13  Symptom 491            51985      3114         5.99
14   Symptom 70              570        32         5.61
15   Symptom 10             1176        66         5.61
16  Symptom 296             1359        75         5.52
17  Symptom 118             1032        52         5.04
18   Symptom 87              829        40         4.83
19  Symptom 116             2394       109         4.55
20  Symptom 127              649        26         4.01
21  Symptom 532             2097        84         4.01
22   Symptom 54              726        27         3.72
23  Symptom 105              716        23         3.21
24  Symptom 517              600        19         3.17
25  Symptom 494             1367        40         2.93
26  Symptom 506             1223        18         1.47
27  Symptom 534             5559        80         1.44
28  Symptom 295              538         5         0.93

In [24]:
u_symptom_details.reset_index()

       u_symptom  Total_incidents  Breaches  Breach_rate
0              ?            32964      2587         7.85
1     Symptom 10             1176        66         5.61
2    Symptom 101               60         7        11.67
3    Symptom 102              880        72         8.18
4    Symptom 103                1         0         0.00
..           ...              ...       ...          ...
521   Symptom 95                3         1        33.33
522   Symptom 96                7         0         0.00
523   Symptom 97               39         1         2.56
524   Symptom 98                8         0         0.00
525   Symptom 99               14         0         0.00

[526 rows x 4 columns]

In [25]:
u_symptom_details.loc[['?']].reset_index()

  u_symptom  Total_incidents  Breaches  Breach_rate
0         ?            32964      2587         7.85

In [26]:
u_symptom_details[(u_symptom_details['Total_incidents']>=500) & (u_symptom_details['Breach_rate']>=6.5)].sort_values(by='Breach_rate',ascending=False)

             Total_incidents  Breaches  Breach_rate
u_symptom
Symptom 208             1112       117        10.52
Symptom 120              930        84         9.03
Symptom 4               2532       225         8.89
Symptom 6                702        62         8.83
Symptom 458              849        71         8.36
Symptom 592              562        46         8.19
Symptom 102              880        72         8.18
Symptom 571             1771       144         8.13
?                      32964      2587         7.85
Symptom 470             1051        79         7.52
Symptom 119              547        41         7.50
Symptom 117              578        42         7.27

In [27]:
u_symptom_details[(u_symptom_details['Total_incidents']>=500) ].sort_values(by='Breaches',ascending=False).reset_index()

      u_symptom  Total_incidents  Breaches  Breach_rate
0   Symptom 491            51985      3114         5.99
1             ?            32964      2587         7.85
2     Symptom 4             2532       225         8.89
3   Symptom 387             2583       163         6.31
4   Symptom 571             1771       144         8.13
5   Symptom 208             1112       117        10.52
6   Symptom 116             2394       109         4.55
7   Symptom 120              930        84         9.03
8   Symptom 532             2097        84         4.01
9   Symptom 534             5559        80         1.44
10  Symptom 470             1051        79         7.52
11  Symptom 296             1359        75         5.52
12  Symptom 102              880        72         8.18
13  Symptom 458              849        71         8.36
14   Symptom 10             1176        66         5.61
15    Symptom 6              702        62         8.83
16  Symptom 118             1032        52         5.04
17  Symptom 592              562        46         8.19
18  Symptom 117              578        42         7.27
19  Symptom 119              547        41         7.50
20  Symptom 494             1367        40         2.93
21   Symptom 87              829        40         4.83
22   Symptom 70              570        32         5.61
23   Symptom 54              726        27         3.72
24  Symptom 127              649        26         4.01
25  Symptom 105              716        23         3.21
26  Symptom 517              600        19         3.17
27  Symptom 506             1223        18         1.47
28  Symptom 295              538         5         0.93

In [28]:
u_symptom_details[(u_symptom_details['Total_incidents']>=500) & (u_symptom_details['Breach_rate']>=6.5)].sort_values(by='Breach_rate',ascending=False).reset_index()

      u_symptom  Total_incidents  Breaches  Breach_rate
0   Symptom 208             1112       117        10.52
1   Symptom 120              930        84         9.03
2     Symptom 4             2532       225         8.89
3     Symptom 6              702        62         8.83
4   Symptom 458              849        71         8.36
5   Symptom 592              562        46         8.19
6   Symptom 102              880        72         8.18
7   Symptom 571             1771       144         8.13
8             ?            32964      2587         7.85
9   Symptom 470             1051        79         7.52
10  Symptom 119              547        41         7.50
11  Symptom 117              578        42         7.27

In [29]:
%store u_symptom_details

Stored 'u_symptom_details' (DataFrame)

In [30]:
eda_df['opened_at'].info()

<class 'pandas.Series'>
RangeIndex: 141712 entries, 0 to 141711
Series name: opened_at
Non-Null Count   Dtype
--------------   -----
141712 non-null  str
dtypes: str(1)
memory usage: 1.1 MB

In [31]:
eda_df['opened_at'].head(1)

0    29/2/2016 01:16
Name: opened_at, dtype: str

In [32]:
from datetime import datetime

In [33]:
eda_df['Hour'] = pd.to_datetime(eda_df['opened_at'], format="%d/%m/%Y %H:%M").dt.hour
eda_df['Day_of_week']=pd.to_datetime(eda_df['opened_at'],format="%d/%m/%Y %H:%M").dt.day_name()
eda_df['Month']=pd.to_datetime(eda_df['opened_at'],format="%d/%m/%Y %H:%M").dt.month_name()

In [34]:
opened_at_details_hour=eda_df.groupby('Hour')['made_sla'].agg(Total_incidents='count',Breaches=lambda x:(~x).sum())
opened_at_details_hour['Breach_rate']=((opened_at_details_hour['Breaches']/opened_at_details_hour['Total_incidents'])*100).round(2)
opened_at_details_hour
%store opened_at_details_hour

Stored 'opened_at_details_hour' (DataFrame)

In [35]:
opened_at_details_day_of_week=eda_df.groupby('Day_of_week')['made_sla'].agg(Total_incidents='count',Breaches=lambda x:(~x).sum())
opened_at_details_day_of_week['Breach_rate']=((opened_at_details_day_of_week['Breaches']/opened_at_details_day_of_week['Total_incidents'])*100).round(2)
opened_at_details_day_of_week

             Total_incidents  Breaches  Breach_rate
Day_of_week
Friday                 21695      1301         6.00
Monday                 33744      2128         6.31
Saturday                3237       135         4.17
Sunday                  2862       157         5.49
Thursday               23472      1566         6.67
Tuesday                28598      1940         6.78
Wednesday              28104      1988         7.07

In [36]:
%store opened_at_details_day_of_week

Stored 'opened_at_details_day_of_week' (DataFrame)

In [37]:
opened_at_details_month=eda_df.groupby('Month')['made_sla'].agg(Total_incidents='count',Breaches=lambda x:(~x).sum())
opened_at_details_month['Breach_rate']=((opened_at_details_month['Breaches']/opened_at_details_month['Total_incidents'])*100).round(2)
opened_at_details_month

           Total_incidents  Breaches  Breach_rate
Month
April                41691      1866         4.48
August                 113         8         7.08
December               187        14         7.49
February              1561        78         5.00
January                610        42         6.89
July                   134         3         2.24
June                    27         1         3.70
March                58012      5477         9.44
May                  39020      1703         4.36
November               139         9         6.47
October                135         9         6.67
September               83         5         6.02

In [38]:
%store opened_at_details_month

Stored 'opened_at_details_month' (DataFrame)

In [39]:
opened_at_details_hour[(opened_at_details_hour['Total_incidents']>=500) & (opened_at_details_hour['Breach_rate']>=6.5)].sort_values(by='Breach_rate',ascending=False)

      Total_incidents  Breaches  Breach_rate
Hour
14              13164      1011         7.68
17               6196       452         7.30
13               9641       691         7.17
15              12290       876         7.13
16              10865       742         6.83
10              16417      1109         6.76
3                 684        46         6.73
11              14827       988         6.66

In [40]:
opened_at_details_day_of_week[(opened_at_details_day_of_week['Total_incidents']>=500) & (opened_at_details_day_of_week['Breach_rate']>=6.5)].sort_values(by='Breach_rate',ascending=False)

             Total_incidents  Breaches  Breach_rate
Day_of_week
Wednesday              28104      1988         7.07
Tuesday                28598      1940         6.78
Thursday               23472      1566         6.67

In [41]:
opened_at_details_month[(opened_at_details_month['Total_incidents']>=500) & (opened_at_details_month['Breach_rate']>=6.5)].sort_values(by='Breach_rate',ascending=False)

         Total_incidents  Breaches  Breach_rate
Month
March              58012      5477         9.44
January              610        42         6.89

In [42]:
time=pd.concat([opened_at_details_hour,opened_at_details_day_of_week,opened_at_details_month],keys=['opened_at_details_hour','opened_at_details_day_of_week','opened_at_details_month'])

In [43]:
time[(time['Total_incidents']>=500) & (time['Breach_rate']>=6.5)].sort_values(by='Breach_rate',ascending=False).sort_index().reset_index()

,level_0,level_1,Total_incidents,Breaches,Breach_rate
0,opened_at_details_day_of_week,Thursday,23472,1566,6.67
1,opened_at_details_day_of_week,Tuesday,28598,1940,6.78
2,opened_at_details_day_of_week,Wednesday,28104,1988,7.07
3,opened_at_details_hour,3,684,46,6.73
4,opened_at_details_hour,10,16417,1109,6.76
5,opened_at_details_hour,11,14827,988,6.66
6,opened_at_details_hour,13,9641,691,7.17
7,opened_at_details_hour,14,13164,1011,7.68
8,opened_at_details_hour,15,12290,876,7.13
9,opened_at_details_hour,16,10865,742,6.83
10,opened_at_details_hour,17,6196,452,7.30
11,opened_at_details_month,January,610,42,6.89
12,opened_at_details_month,March,58012,5477,9.44

In [44]:
print(eda_df['caller_id'].unique())
print("-----------------------------------")
print("Unique value count:",eda_df['caller_id'].unique().shape[0])
print("-----------------------------------")
print(eda_df['caller_id'].sort_values(ascending=False).head(10))
print("-----------------------------------")
print("Null values: ",eda_df['caller_id'].isnull().sum())
print("-----------------------------------")
print("Unknown values :",(eda_df['caller_id']=='?').sum())

<StringArray>
['Caller 2403', 'Caller 4416', 'Caller 4491', 'Caller 3765', 'Caller 2146',
 'Caller 2838', 'Caller 5323', 'Caller 3796',  'Caller 442', 'Caller 3757',
 ...
 'Caller 1768',  'Caller 454',  'Caller 646',  'Caller 712', 'Caller 4418',
 'Caller 3328', 'Caller 2986', 'Caller 1384', 'Caller 5100', 'Caller 1899']
Length: 5245, dtype: str
-----------------------------------
Unique value count: 5245
-----------------------------------
19968    Caller 999
14071    Caller 999
37270    Caller 999
35762    Caller 999
94282    Caller 999
35761    Caller 999
94281    Caller 999
35760    Caller 999
91547    Caller 999
35759    Caller 999
Name: caller_id, dtype: str
-----------------------------------
Null values:  0
-----------------------------------
Unknown values : 29

In [45]:
print(eda_df['opened_by'].unique())
print("-----------------------------------")
print("Unique value count:",eda_df['opened_by'].unique().shape[0])
print("-----------------------------------")
print(eda_df['opened_by'].sort_values(ascending=False).head(10))
print("-----------------------------------")
print("Null values: ",eda_df['opened_by'].isnull().sum())
print("-----------------------------------")
print("Unknown values :",(eda_df['opened_by']=='?').sum())

<StringArray>
[  'Opened by  8', 'Opened by  397', 'Opened by  180', 'Opened by  131',
  'Opened by  24',  'Opened by  40', 'Opened by  433',  'Opened by  62',
 'Opened by  501', 'Opened by  301',
 ...
 'Opened by  452', 'Opened by  488', 'Opened by  389', 'Opened by  273',
 'Opened by  211',   'Opened by  7',  'Opened by  88', 'Opened by  271',
 'Opened by  508', 'Opened by  490']
Length: 208, dtype: str
-----------------------------------
Unique value count: 208
-----------------------------------
136486    Opened by  94
83528     Opened by  94
83549     Opened by  94
83531     Opened by  94
83530     Opened by  94
96910     Opened by  94
96911     Opened by  94
96912     Opened by  94
83529     Opened by  94
83527     Opened by  94
Name: opened_by, dtype: str
-----------------------------------
Null values:  0
-----------------------------------
Unknown values : 4835

In [46]:
# caller_id_details=eda_df.groupby('caller_id')['made_sla'].agg(Total_incidents='count',Breaches=lambda x:(~x).sum())
# caller_id_details['Breach_rate']=((caller_id_details['Breaches']/caller_id_details['Total_Incidents'])*100).round(2)

In [47]:
%store eda_df

Stored 'eda_df' (DataFrame)

In [48]:
eda_df

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at,Hour,Day_of_week,Month
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00,1,Monday,February
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00,1,Monday,February
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00,1,Monday,February
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00,1,Monday,February
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00,4,Monday,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141707,INC0120835,Closed,False,1,0,4,True,Caller 116,Opened by 12,16/2/2017 09:09,...,?,?,?,code 9,Resolved by 9,16/2/2017 09:53,16/2/2017 09:53,9,Thursday,February
141708,INC0121064,Active,True,0,0,0,True,Caller 116,Opened by 12,16/2/2017 14:17,...,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38,14,Thursday,February
141709,INC0121064,Active,True,1,0,1,True,Caller 116,Opened by 12,16/2/2017 14:17,...,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38,14,Thursday,February
141710,INC0121064,Resolved,True,1,0,2,True,Caller 116,Opened by 12,16/2/2017 14:17,...,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38,14,Thursday,February
141711,INC0121064,Closed,False,1,0,3,True,Caller 116,Opened by 12,16/2/2017 14:17,...,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38,14,Thursday,February