# Model Training

Objective:
Build a machine learning pipeline capable of predicting SLA breaches at incident creation time.

The modeling phase includes:

- Preprocessing Pipeline
- Missing Value Handling
- Encoding
- Class Imbalance Handling
- Model Training
- Cross Validation
- Hyperparameter Tuning
- Model Selection

# Import Libraries

In [123]:
import pandas as pd
import numpy as np
import calendar
from pandas.api.types import is_object_dtype, is_string_dtype
from sklearn.utils.validation import check_is_fitted
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder,TargetEncoder,FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,roc_auc_score
from sklearn.model_selection import cross_val_score

# Load Processed Data

In [124]:
X_train=pd.read_csv('../../data/processed/X_train.csv')
X_test=pd.read_csv('../../data/processed/X_test.csv')
y_train=pd.read_csv('../../data/processed/y_train.csv')
y_test=pd.read_csv('../../data/processed/y_test.csv')

# Feature Groups

| Feature Group      | Features                                                        |
| ------------------ | --------------------------------------------------------------- |
| Frequency Encoding | category, subcategory, assignment_group, assigned_to, opened_by |
| Target Encoding    | caller_id, location, u_symptom, contact_type                    |
| Ordinal Encoding   | impact, urgency, priority                                       |
| Numerical          | Hour                                                            |
| Calendar Features  | Month, Day_of_week                                              |
                                          |

## Preprocessing Pipeline Design

### Traditional ML Pipeline

Missing Value Replacement
        ↓
Ordinal Encoding
        ↓
Frequency Encoding
        ↓
Target Encoding
        ↓
Model

### CatBoost Pipeline

Missing Value Replacement
        ↓
Ordinal Encoding
        ↓
Native Categorical Handling
        ↓
CatBoost

# Custom Transformers

In [125]:

replacement={
    'location': 'Unknown_location',
    'category':'Unknown_category',
    'subcategory':'Unknown_subcategory',
    'u_symptom':'Unknown_symptom',
    'assignment_group':'Unknown_assignment_group',
    'assigned_to':'Unknown_assigned_to',
    'caller_id': 'Unknown_caller_id',
    'opened_by':'Unknown_opened_by'
}

nested_replacement={col: {'?':val} for col, val in replacement.items()}

def replace_missing_value(X):
    X_copy=X.copy()
    return X_copy.replace(nested_replacement)

missing_value_imputer = FunctionTransformer(replace_missing_value)

missing_values_pipeline=Pipeline([('impute_missing_value',missing_value_imputer)])

In [126]:
from sklearn.base import BaseEstimator, TransformerMixin

class BusinessMissingValueTransformer(BaseEstimator, TransformerMixin):

    def __init__(self):
        self.replacement = {
            'location': 'Unknown_location',
            'category': 'Unknown_category',
            'subcategory': 'Unknown_subcategory',
            'u_symptom': 'Unknown_symptom',
            'assignment_group': 'Unknown_assignment_group',
            'assigned_to': 'Unknown_assigned_to',
            'caller_id': 'Unknown_caller_id',
            'opened_by': 'Unknown_opened_by'
        }

        self.missing_tokens = ['?', 'NA', 'N/A', None]

    def fit(self, X, y=None):

        missing_cols = []

        for col in self.replacement.keys():
            if col not in X.columns:
                missing_cols.append(col)

        if missing_cols:
            raise ValueError(
                f"Required missing columns are: {missing_cols}"
            )

        return self

    def transform(self, X):

        X_copy = X.copy()

        for col, replacement_value in self.replacement.items():

            X_copy[col] = X_copy[col].replace(
                self.missing_tokens,
                replacement_value
            )

        return X_copy

In [127]:
missing_transformer = BusinessMissingValueTransformer()

missing_transformer.fit(X_train)

X_train_transformed = missing_transformer.transform(X_train)

In [128]:
(X_train_transformed[
    ['location','category','subcategory',
     'u_symptom','assignment_group',
     'assigned_to','caller_id','opened_by']
].isin(['?','NA','N/A']).sum())

location            0
category            0
subcategory         0
u_symptom           0
assignment_group    0
assigned_to         0
caller_id           0
opened_by           0
dtype: int64

In [129]:
X_train['priority'].value_counts()

priority
3 - Moderate    105935
4 - Low           3226
2 - High          2385
1 - Critical      1823
Name: count, dtype: int64

In [130]:
# Ordinal Transformer

class OrdinalTransformer(BaseEstimator,TransformerMixin):
    """
    Custom transformer to perform business-rule-based ordinal encoding.

    Features:
    - Validates required columns.
    - Detects unseen categories before transformation.
    - Encodes Impact, Urgency and Priority based on predefined business mappings.
    - Raises descriptive exceptions when unexpected categories are encountered.
    - Compatible with Scikit-Learn Pipelines.
    """
    def __init__(self,ordinal_mappings=None):
        if ordinal_mappings is None:
            self.ordinal_mappings={
                'impact':{
                    '3 - Low':1,
                    '2 - Medium':2,
                    '1 - High':3
                },
                'urgency':{
                    '3 - Low':1,
                    '2 - Medium':2,
                    '1 - High':3
                },
                'priority':{
                    '4 - Low':1,
                    '3 - Moderate':2,
                    '2 - High':3,
                    '1 - Critical':4
                }
            }
        else:
            """To build this as a reusable package, I am inject the mappings through the constructor with a default configuration."""
            self.ordinal_mappings = ordinal_mappings ## using this line we can use this transformer in any project

    def _validate_input(self,X):
         if not isinstance(X,pd.DataFrame):
              raise TypeError(f"Expected a pandas DataFrame, but got {type(X).__name__}")
    
    def _validate_columns(self,X):
        """Helper method to ensure all expected mapping columns exist in the dataset."""
        missing_columns=[col for col in self.ordinal_mappings.keys() if col not in X.columns]
        if missing_columns:
            raise ValueError(f"Required missing columns are :{missing_columns}") 
        

    def fit(self,X,y=None):
        """
        Validate that all required ordinal columns are present.
        """
        self._validate_input(X)
        self._validate_columns(X)
        return self

    def transform(self,X):
        """
        Validate ordinal values and apply business-rule-based encoding.
        """
        self._validate_input(X)
        self._validate_columns(X)
        
        X_copy=X.copy()
        invalid_values={}

        for col,mapping in self.ordinal_mappings.items():
            diff=set(X_copy[col].unique()) - set(mapping.keys())
            if diff:
                 invalid_values[col]=diff
        
        if invalid_values:
            raise ValueError(f"Unknown categorical values found during transformation: {invalid_values}")
        
        for col,value in self.ordinal_mappings.items():
            X_copy[col]=X_copy[col].map(value)
            
        return X_copy
        
ordinal_transformer = OrdinalTransformer()

X_train_ordinal = ordinal_transformer.fit_transform(X_train)
X_train_ordinal[['impact','urgency','priority']]

        impact  urgency  priority
0            2        2         2
1            2        2         2
2            2        2         2
3            2        2         2
4            2        2         2
...        ...      ...       ...
113364       2        2         2
113365       2        2         2
113366       2        2         2
113367       2        2         2
113368       2        2         2

[113369 rows x 3 columns]

In [131]:
#Frequency Encoder

class FrequencyEncoder(BaseEstimator,TransformerMixin):
    """
    Custom transformer to perform frequency encoding.

    Features:
        - Learns normalized frequencies from training data.
        - Encodes configured high-cardinality categorical features.
        - Handles unseen categories using a configurable unknown_value.
        - Compatible with Scikit-Learn Pipelines.
    """
    def __init__(self,frequency_columns=None,unknown_value=0.0):
        if frequency_columns is None:
            self.frequency_columns=[
            'category',
            'subcategory',
            'assignment_group',
            'assigned_to',
            'opened_by'
            ]
        else:
            self.frequency_columns=frequency_columns

        self.frequency_mappings={}
        self.unknown_value = unknown_value
    
    def _validate_input(self,X):
        if not isinstance(X,pd.DataFrame):
              raise TypeError(f"Expected a pandas DataFrame, but got {type(X).__name__}")
    
    def _validate_columns(self,X):
        missing_columns=[col for col in self.frequency_columns if col not in X.columns]
        if missing_columns:
            raise ValueError(f"Required missing columns are :{missing_columns}")
        
    def fit(self,X,y=None):
        self._validate_input(X)
        self._validate_columns(X)
        self.frequency_mappings={
          col:X[col].value_counts(normalize=True).to_dict()  for col in self.frequency_columns
        }
        
        return self

    def transform(self,X,y=None):
        self._validate_input(X)
        self._validate_columns(X)
        X_copy=X.copy()

        if not self.frequency_mappings:
            raise ValueError(
                "FrequencyEncoder has not been fitted yet. "
                "Call fit() before transform()."
                )
        
        for col, mapping in self.frequency_mappings.items():
            X_copy[col] = X_copy[col].map(mapping)

            X_copy[col] = X_copy[col].fillna(self.unknown_value)
            
        return X_copy


encoder = FrequencyEncoder()

encoder.fit(X_train)

X_train_encoded = encoder.transform(X_train)
X_train_encoded

       contact_type      location  category  ...  Hour Day_of_week     Month
0             Phone  Location 204  0.045938  ...    13      Sunday       May
1             Phone  Location 143  0.112879  ...    14      Monday  February
2             Phone  Location 234  0.026621  ...    14   Wednesday     March
3             Phone  Location 161  0.026621  ...     8     Tuesday     March
4             Phone  Location 143  0.051698  ...    16    Thursday     March
...             ...           ...       ...  ...   ...         ...       ...
113364        Phone   Location 38  0.112879  ...    14     Tuesday       May
113365        Phone  Location 143  0.130080  ...    14     Tuesday     March
113366        Phone   Location 54  0.112879  ...    13   Wednesday     April
113367        Phone   Location 55  0.093800  ...    10      Friday     April
113368        Phone  Location 179  0.051698  ...    21      Friday     March

[113369 rows x 15 columns]

In [132]:
encoder = FrequencyEncoder(unknown_value=0.0)
encoder.fit(X_train)

# Clean naming convention to keep track of splits
X_test_encoded = encoder.transform(X_test)
X_test_encoded

      contact_type      location  category  ...  Hour Day_of_week  Month
0            Phone   Location 56  0.055386  ...    18      Monday    May
1            Phone   Location 93  0.112412  ...     8    Thursday    May
2            Phone  Location 204  0.046547  ...     8     Tuesday    May
3            Phone  Location 204  0.130080  ...     8    Thursday  April
4            Phone   Location 59  0.130080  ...    10      Monday  March
...            ...           ...       ...  ...   ...         ...    ...
28338        Phone  Location 161  0.055386  ...    12      Monday  April
28339        Phone  Location 108  0.130080  ...     9     Tuesday  April
28340        Phone  Location 204  0.130080  ...     8     Tuesday  April
28341        Phone   Location 93  0.112879  ...     7      Monday  April
28342        Phone  Location 131  0.112412  ...    10      Sunday  March

[28343 rows x 15 columns]

In [133]:
# Filters the DataFrame to only your processed columns and checks for 0.0
zero_counts = (X_test_encoded[encoder.frequency_columns] == 0.0).sum()

print("Count of 0.0 values per column:")
print(zero_counts)

Count of 0.0 values per column:
category            0
subcategory         1
assignment_group    1
assigned_to         0
opened_by           3
dtype: int64

In [134]:
class TargetEncoder(BaseEstimator, TransformerMixin):
    """Custom transformer to perform target encoding with additive smoothing.

    This encoder replaces categorical values with the smoothed mean of the 
    target variable for that specific category. It balances the local category 
    mean against the global target mean to mitigate overfitting in high-cardinality 
    features or small sample sizes.

    Parameters
    ----------
    target_columns : list of str, default=None
        The columns in the input DataFrame to be target encoded. If None, 
        defaults to ['caller_id', 'location', 'u_symptom', 'contact_type'].
    target_column : str, default='made_sla'
        The column name of the target variable used to search inside `y` if 
        it is passed as a pandas DataFrame.
    smoothing : int or float, default=10
        The smoothing factor (m-estimate constant). Higher values pull category 
        means closer to the global mean, acting as a stronger regularizer.

    Attributes
    ----------
    target_mappings : dict
        Nested dictionary mapping feature names to dictionaries of encoded category values.
    global_mean : float
        The overall mean of the target variable across the entire training set.
    n_features_in_ : tuple
        The shape dimensions of the feature matrix seen during `fit`.
    """
    
    def __init__(self, target_columns=None, target_column='made_sla', smoothing=10):
        if target_columns is None:
            self.target_columns = ['caller_id', 'location', 'u_symptom', 'contact_type']
        else:
            self.target_columns = target_columns
            
        self.target_column = target_column
        self.smoothing = smoothing
        self.target_mappings = {}
        self.global_mean = None

    def _validate_X(self, X):
        """Validates input structural data type for the feature matrix X."""
        if not isinstance(X, pd.DataFrame):
            raise TypeError(f"Expected X to be a pandas DataFrame, but got {type(X).__name__}")

    def _validate_y(self, y):
        """Validates input structural data types, dimensions, and naming for the target vector y."""
        if not isinstance(y, (pd.Series, pd.DataFrame, np.ndarray)):
            raise TypeError(f"Expected y to be a Series, DataFrame, or array, but got {type(y).__name__}")
        
        if isinstance(y, pd.DataFrame) and self.target_column not in y.columns:
            raise ValueError(f"The target column '{self.target_column}' is missing from the target DataFrame.")
            
        if isinstance(y, np.ndarray) and y.ndim != 1:
            raise ValueError(f"Expected y to be a 1D array, but got a {y.ndim}D array instead.")

    def _validate_columns(self, X):
        """Verifies that all specified feature columns exist in the DataFrame."""
        missing_columns = [col for col in self.target_columns if col not in X.columns]
        if missing_columns:    
            raise ValueError(f"Required missing columns are: {missing_columns}")

    def _compute_smoothed_mean(self, group_stats):
        """Calculates the smoothed target value using the explicit local variables layout."""
        numerator = (group_stats['count'] * group_stats['mean']) + (self.smoothing * self.global_mean)
        denominator = group_stats['count'] + self.smoothing
        return numerator / denominator

    def fit(self, X, y):
        """Fit the target encoder by calculating smoothed category means.

        Parameters
        ----------
        X : pandas.DataFrame
            The feature matrix containing columns to encode.
        y : pandas.Series, pandas.DataFrame, or numpy.ndarray
            The target vector.

        Returns
        -------
        self : object
            Returns the instance itself.
        """
        self._validate_X(X)
        self._validate_y(y)
        self._validate_columns(X)
        
        self.n_features_in_ = X.shape[1]
        
        if isinstance(y, pd.DataFrame):
            y_series = y[self.target_column]
        elif isinstance(y, pd.Series):
            y_series = y
        else:
            y_series = pd.Series(y, index=X.index)

        self.global_mean = y_series.mean()
        self.target_mappings = {}

        for col in self.target_columns:
            encoding_df = pd.concat([X[col], y_series.rename(self.target_column)], axis=1)
            group_stats = encoding_df.groupby(col)[self.target_column].agg(['mean', 'count'])

            group_stats['smoothed'] = self._compute_smoothed_mean(group_stats)
            self.target_mappings[col] = group_stats['smoothed'].to_dict()
             
        return self
    
    def transform(self, X):
        """Transform the categorical columns using the learned target mappings.

        Unseen categories encountered during testing will be imputed with 
        the global training mean.

        Parameters
        ----------
        X : pandas.DataFrame
            The feature matrix to transform.

        Returns
        -------
        X_transformed : pandas.DataFrame
            The transformed DataFrame with numerical target-encoded features.
        """
        self._validate_X(X)
        self._validate_columns(X)
        
        check_is_fitted(self, "n_features_in_")

        X_transformed = X.copy()
        for col, mapping in self.target_mappings.items():
            X_transformed[col] = (X_transformed[col].map(mapping).fillna(self.global_mean))
    

        return X_transformed
                 

    def get_feature_names_out(self, input_features=None):
        """Returns feature names out for Scikit-Learn pipeline support."""
        if input_features is None:
            return np.array(self.target_columns)
        return np.array(input_features)

In [135]:
target_encoder=TargetEncoder().fit(X_train,y_train)

In [136]:
target_encoder.transform(X_test)

       contact_type  location     category  ... Hour  Day_of_week  Month
0          0.064774  0.071731  Category 23  ...   18       Monday    May
1          0.064774  0.066701  Category 53  ...    8     Thursday    May
2          0.064774  0.070246  Category 37  ...    8      Tuesday    May
3          0.064774  0.070246  Category 26  ...    8     Thursday  April
4          0.064774  0.063069  Category 26  ...   10       Monday  March
...             ...       ...          ...  ...  ...          ...    ...
28338      0.064774  0.051274  Category 23  ...   12       Monday  April
28339      0.064774  0.058719  Category 26  ...    9      Tuesday  April
28340      0.064774  0.070246  Category 26  ...    8      Tuesday  April
28341      0.064774  0.066701  Category 42  ...    7       Monday  April
28342      0.064774  0.050884  Category 53  ...   10       Sunday  March

[28343 rows x 15 columns]

In [137]:
X_train[['Hour', 'Month', 'Day_of_week']].dtypes

Hour           int64
Month            str
Day_of_week      str
dtype: object

In [138]:
X_train[['Hour', 'Month', 'Day_of_week']].describe()

                Hour
count  113369.000000
mean       11.886080
std         4.012372
min         0.000000
25%         9.000000
50%        11.000000
75%        15.000000
max        23.000000

In [139]:
X_train[ 'Month'].unique()

<StringArray>
[      'May',  'February',     'March',     'April',   'January',   'October',
    'August',  'December', 'September',      'July',  'November',      'June']
Length: 12, dtype: str

In [140]:
class CyclicEncoder(BaseEstimator, TransformerMixin):
    """
    Parameters
    ----------
        cyclic_columns : dict, default=None
            Dictionary mapping cyclic feature names to their cycle lengths.

        drop_original : bool, default=True
            Whether to remove the original cyclic columns after encoding.

    Attributes
    ----------
        month_mapping : dict
        day_mapping : dict
        n_features_in_ : int
    """
    def __init__(self,cyclic_columns=None,drop_original=True):
        if cyclic_columns is None:
            self.cyclic_columns={
                'Hour':24,
                'Day_of_week':7,
                'Month':12
            }
        else:
            self.cyclic_columns=cyclic_columns

        self.drop_original=drop_original
        self.month_mapping={
            month:idx for idx,month in enumerate(calendar.month_name) if month
            }
        self.day_mapping={ 
            day:idx for idx,day in enumerate(calendar.day_name) if day
            }
        
        self.category_mappings = {
            "Month": self.month_mapping,
            "Day_of_week": self.day_mapping
        }
        
    
    def _validate_input(self,X):
        if not isinstance(X,pd.DataFrame):
            raise TypeError(f"Expected the pandas Dataframe to be, but got: {type(X).__name__} ")
    
    def _validate_columns(self,X):
        missing_columns=[col for col in self.cyclic_columns if col not in X.columns]
        if missing_columns:    
            raise ValueError(f"Required missing columns are: {missing_columns}") 

    def fit(self,X,y=None):
        self._validate_input(X)
        self._validate_columns(X)
        self.n_features_in_ = X.shape[1]
        return self

    def transform(self,X):
        self._validate_input(X)
        self._validate_columns(X)
        check_is_fitted(self, "n_features_in_")
        X_transformed=X.copy()

        for col, mapping in self.category_mappings.items():
            if col in self.cyclic_columns:
                if is_object_dtype(X_transformed[col]) or is_string_dtype(X_transformed[col]):
                    X_transformed[col] = X_transformed[col].map(mapping)

        for col,period in self.cyclic_columns.items():
                        
            numeric_values = pd.to_numeric(X_transformed[col],errors='raise')

            X_transformed[f'{col}_sin']=np.sin((2*np.pi*numeric_values)/period)
            X_transformed[f'{col}_cos']=np.cos((2*np.pi*numeric_values)/period)
            
        if self.drop_original:
            X_transformed=X_transformed.drop(columns=list(self.cyclic_columns.keys()),errors='ignore')

        return X_transformed

In [141]:
cyclic=CyclicEncoder().fit(X_train,y_train)

In [142]:
cyclic.transform(X_test)

      contact_type      location  ... Month_sin     Month_cos
0            Phone   Location 56  ...  0.500000 -8.660254e-01
1            Phone   Location 93  ...  0.500000 -8.660254e-01
2            Phone  Location 204  ...  0.500000 -8.660254e-01
3            Phone  Location 204  ...  0.866025 -5.000000e-01
4            Phone   Location 59  ...  1.000000  6.123234e-17
...            ...           ...  ...       ...           ...
28338        Phone  Location 161  ...  0.866025 -5.000000e-01
28339        Phone  Location 108  ...  0.866025 -5.000000e-01
28340        Phone  Location 204  ...  0.866025 -5.000000e-01
28341        Phone   Location 93  ...  0.866025 -5.000000e-01
28342        Phone  Location 131  ...  1.000000  6.123234e-17

[28343 rows x 18 columns]

In [143]:
month_mapping={
            month:idx for idx,month in enumerate(calendar.month_name) if month
            }
for col,mapping in month_mapping.items():
    print(col,mapping)

January 1
February 2
March 3
April 4
May 5
June 6
July 7
August 8
September 9
October 10
November 11
December 12

## Modeling Strategy

Baseline Models
- Logistic Regression
- Decision Tree
- Random Forest

Boosting Models
- XGBoost
- LightGBM
- CatBoost

Evaluation Metrics
- Precision
- Recall
- F1 Score
- ROC-AUC
- PR-AUC

Cross Validation
- Stratified K-Fold

Hyperparameter Optimization
- Optuna

# Preprocessing Pipeline

In [144]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (accuracy_score,
                             precision_score,
                             recall_score,
                             f1_score,
                             roc_auc_score,
                             confusion_matrix,
                             classification_report
                        )

In [145]:
preprocessing_pipeline=Pipeline(steps=[
    ("Business_missing",BusinessMissingValueTransformer()),
    ("ordinal_encoding",OrdinalTransformer()),
    ("Frequency_encoding",FrequencyEncoder()),
    ("Target_encoding",TargetEncoder()),
    ("Cyclic_encoding",CyclicEncoder())
])

X_train_processed=preprocessing_pipeline.fit_transform(X_train,y_train)
X_test_processed=preprocessing_pipeline.transform(X_test)

## Preprocessing Pipeline Validation

In [146]:
X_train_processed.shape,X_test_processed.shape

((113369, 18), (28343, 18))

In [147]:
X_train_processed.dtypes,X_test_processed.dtypes

(contact_type        float64
 location            float64
 category            float64
 subcategory         float64
 u_symptom           float64
 assignment_group    float64
 assigned_to         float64
 caller_id           float64
 opened_by           float64
 impact                int64
 urgency               int64
 priority              int64
 Hour_sin            float64
 Hour_cos            float64
 Day_of_week_sin     float64
 Day_of_week_cos     float64
 Month_sin           float64
 Month_cos           float64
 dtype: object,
 contact_type        float64
 location            float64
 category            float64
 subcategory         float64
 u_symptom           float64
 assignment_group    float64
 assigned_to         float64
 caller_id           float64
 opened_by           float64
 impact                int64
 urgency               int64
 priority              int64
 Hour_sin            float64
 Hour_cos            float64
 Day_of_week_sin     float64
 Day_of_week_cos     float64
 Month_sin           float64
 Month_cos           float64
 dtype: object)

In [148]:
X_train_processed.isnull().sum(),X_test_processed.isnull().sum()

(contact_type        0
 location            0
 category            0
 subcategory         0
 u_symptom           0
 assignment_group    0
 assigned_to         0
 caller_id           0
 opened_by           0
 impact              0
 urgency             0
 priority            0
 Hour_sin            0
 Hour_cos            0
 Day_of_week_sin     0
 Day_of_week_cos     0
 Month_sin           0
 Month_cos           0
 dtype: int64,
 contact_type        0
 location            0
 category            0
 subcategory         0
 u_symptom           0
 assignment_group    0
 assigned_to         0
 caller_id           0
 opened_by           0
 impact              0
 urgency             0
 priority            0
 Hour_sin            0
 Hour_cos            0
 Day_of_week_sin     0
 Day_of_week_cos     0
 Month_sin           0
 Month_cos           0
 dtype: int64)

In [149]:
X_train_processed.columns,X_test_processed.columns

(Index(['contact_type', 'location', 'category', 'subcategory', 'u_symptom',
        'assignment_group', 'assigned_to', 'caller_id', 'opened_by', 'impact',
        'urgency', 'priority', 'Hour_sin', 'Hour_cos', 'Day_of_week_sin',
        'Day_of_week_cos', 'Month_sin', 'Month_cos'],
       dtype='str'),
 Index(['contact_type', 'location', 'category', 'subcategory', 'u_symptom',
        'assignment_group', 'assigned_to', 'caller_id', 'opened_by', 'impact',
        'urgency', 'priority', 'Hour_sin', 'Hour_cos', 'Day_of_week_sin',
        'Day_of_week_cos', 'Month_sin', 'Month_cos'],
       dtype='str'))

In [150]:
X_train_processed.columns==X_test_processed.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [151]:
X_train_processed.describe()

        contact_type       location  ...      Month_sin     Month_cos
count  113369.000000  113369.000000  ...  113369.000000  1.133690e+05
mean        0.065022       0.064996  ...       0.810127 -3.757497e-01
std         0.004616       0.013620  ...       0.232300  3.854145e-01
min         0.026011       0.013005  ...      -1.000000 -1.000000e+00
25%         0.064774       0.058719  ...       0.500000 -8.660254e-01
50%         0.064774       0.068419  ...       0.866025 -5.000000e-01
75%         0.064774       0.070246  ...       1.000000  6.123234e-17
max         0.178044       0.173005  ...       1.000000  1.000000e+00

[8 rows x 18 columns]

In [152]:
X_test_processed.describe()

       contact_type      location  ...     Month_sin     Month_cos
count  28343.000000  28343.000000  ...  28343.000000  2.834300e+04
mean       0.065004      0.064978  ...      0.811726 -3.724143e-01
std        0.004449      0.013525  ...      0.229907  3.867281e-01
min        0.026011      0.013005  ...     -1.000000 -1.000000e+00
25%        0.064774      0.058719  ...      0.500000 -8.660254e-01
50%        0.064774      0.068419  ...      0.866025 -5.000000e-01
75%        0.064774      0.070246  ...      1.000000  6.123234e-17
max        0.178044      0.173005  ...      1.000000  1.000000e+00

[8 rows x 18 columns]

In [153]:
print(f"Training Shape : {X_train_processed.shape}")
print(f"Testing Shape  : {X_test_processed.shape}")

print("\nTraining Missing Values")
print(X_train_processed.isna().sum().sum())

print("\nTesting Missing Values")
print(X_test_processed.isna().sum().sum())

print("\nChecking '?' values in Training Data")
print((X_train_processed == '?').sum())

print("\nChecking '?' values in Testing Data")
print((X_test_processed == '?').sum())

Training Shape : (113369, 18)
Testing Shape  : (28343, 18)

Training Missing Values
0

Testing Missing Values
0

Checking '?' values in Training Data
contact_type        0
location            0
category            0
subcategory         0
u_symptom           0
assignment_group    0
assigned_to         0
caller_id           0
opened_by           0
impact              0
urgency             0
priority            0
Hour_sin            0
Hour_cos            0
Day_of_week_sin     0
Day_of_week_cos     0
Month_sin           0
Month_cos           0
dtype: int64

Checking '?' values in Testing Data
contact_type        0
location            0
category            0
subcategory         0
u_symptom           0
assignment_group    0
assigned_to         0
caller_id           0
opened_by           0
impact              0
urgency             0
priority            0
Hour_sin            0
Hour_cos            0
Day_of_week_sin     0
Day_of_week_cos     0
Month_sin           0
Month_cos           0
dtype: int64

In [154]:
logestic_regression=LogisticRegression(class_weight='balanced',random_state=42,max_iter=1000)

In [155]:
y_train_processed=y_train.to_numpy().reshape(-1,)

In [156]:
logestic_regression.fit(X_train_processed,y_train.values.ravel())

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [157]:
y_pred=logestic_regression.predict(X_test_processed)

In [158]:
y_prob = logestic_regression.predict_proba(X_test_processed)[:, 1]

In [159]:
baseline_results = {
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1 Score": f1_score(y_test, y_pred),
    "ROC-AUC": roc_auc_score(y_test, y_prob)
}

for metric, value in baseline_results.items():
    print(f"{metric:<12}: {value:.4f}")

Accuracy    : 0.6543
Precision   : 0.0936
Recall      : 0.4970
F1 Score    : 0.1575
ROC-AUC     : 0.6366

In [160]:
def evaluate_model(model_name,y_true,y_pred,y_prob):
    """
    Evaluate classification model performance.

    Parameters
    ----------
    y_true : array-like
        Actual target values.

    y_pred : array-like
        Predicted class labels.

    y_prob : array-like
        Predicted probabilities for the positive class.

    Returns
    -------
    dict
        Dictionary containing evaluation metrics and reports.
    """
    report_df = pd.DataFrame(classification_report(y_true, y_pred, output_dict=True)).T
    logistic_results={
        "Model":model_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1 Score": f1_score(y_true, y_pred),
        "ROC-AUC": roc_auc_score(y_true, y_prob),
        "Test Samples": len(y_true),
        "Confusion Matrix": confusion_matrix(y_true, y_pred),
        "Classification Report": report_df
    }
    for metric, value in logistic_results.items():
        if metric not in ["Confusion Matrix", "Classification Report"]:
            print(f"{metric:<15}: {value}")
            
    print("\nConfusion Matrix")
    print(logistic_results["Confusion Matrix"])

    print("\nClassification Report")
    display(logistic_results["Classification Report"])

In [161]:
evaluate_model('Logistic Regression',y_true=y_test,y_pred=y_pred,y_prob=y_prob)

Model          : Logistic Regression
Accuracy       : 0.6543061778922485
Precision      : 0.09359354245427608
Recall         : 0.49701573521432446
F1 Score       : 0.15752364574376612
ROC-AUC        : 0.6366003132710203
Test Samples   : 28343

Confusion Matrix
[[17629  8871]
 [  927   916]]

Classification Report

              precision    recall  f1-score       support
0              0.950043  0.665245  0.782537  26500.000000
1              0.093594  0.497016  0.157524   1843.000000
accuracy       0.654306  0.654306  0.654306      0.654306
macro avg      0.521818  0.581131  0.470030  28343.000000
weighted avg   0.894353  0.654306  0.741896  28343.000000

In [162]:
decision_tree=DecisionTreeClassifier(criterion='gini',max_depth=10,class_weight='balanced',random_state=42)

In [163]:
decision_tree.fit(X_train_processed,y_train.values.ravel())

DecisionTreeClassifier(class_weight='balanced', max_depth=10, random_state=42)

In [164]:
y_pred_dt=decision_tree.predict(X_test_processed)

In [165]:
y_prob_dt=decision_tree.predict_proba(X_test_processed)[:,1]

In [166]:
evaluate_model('Decision Tree',y_true=y_test,y_pred=y_pred_dt,y_prob=y_prob_dt)

Model          : Decision Tree
Accuracy       : 0.6097449105599266
Precision      : 0.09633911368015415
Recall         : 0.5968529571351058
F1 Score       : 0.16590000754090944
ROC-AUC        : 0.6228043694141013
Test Samples   : 28343

Confusion Matrix
[[16182 10318]
 [  743  1100]]

Classification Report

              precision    recall  f1-score       support
0              0.956100  0.610642  0.745285  26500.000000
1              0.096339  0.596853  0.165900   1843.000000
accuracy       0.609745  0.609745  0.609745      0.609745
macro avg      0.526220  0.603747  0.455592  28343.000000
weighted avg   0.900195  0.609745  0.707611  28343.000000

In [167]:
random_forest=RandomForestClassifier(n_estimators=100,class_weight='balanced',max_depth=10,max_features='sqrt',bootstrap=True,criterion='gini',random_state=42)

In [168]:
random_forest.fit(X_train_processed,y_train.values.ravel())

RandomForestClassifier(class_weight='balanced', max_depth=10, random_state=42)

In [169]:
y_pred_rf=random_forest.predict(X_test_processed)

In [170]:
y_prob_rf=random_forest.predict_proba(X_test_processed)[:,1]

In [171]:
evaluate_model('Random Forest',y_true=y_test.values.ravel(),y_pred=y_pred_rf,y_prob=y_prob_rf)

Model          : Random Forest
Accuracy       : 0.6374413435416152
Precision      : 0.09584970765839164
Recall         : 0.5425935973955507
F1 Score       : 0.16291951775822744
ROC-AUC        : 0.64540204138044
Test Samples   : 28343

Confusion Matrix
[[17067  9433]
 [  843  1000]]

Classification Report

              precision    recall  f1-score       support
0              0.952931  0.644038  0.768611  26500.000000
1              0.095850  0.542594  0.162920   1843.000000
accuracy       0.637441  0.637441  0.637441      0.637441
macro avg      0.524391  0.593316  0.465765  28343.000000
weighted avg   0.897200  0.637441  0.729226  28343.000000

# Hyperparamters Tuning

In [172]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
import optuna
from sklearn.model_selection import StratifiedKFold

In [173]:
def objective(trial):
    n_estimators=trial.suggest_int('n_estimators',50,500,step=50)
    max_depth=trial.suggest_int('max_depth',5,19,step=2)
    min_samples_split=trial.suggest_int('min_samples_split',2,20,step=1)
    min_samples_leaf=trial.suggest_int('min_samples_leaf',1,10,step=1)
    max_features=trial.suggest_categorical('max_features',['sqrt','log2',None])
    
    random_forest_tune=RandomForestClassifier(n_estimators=n_estimators,max_depth=max_depth,
                                              min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf,
                                              max_features=max_features,class_weight='balanced',
                                              bootstrap=True,criterion='gini',random_state=42,n_jobs=-1)
    
    cv_f1_score=[]
    skf=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

    for train_idx,valid_idx in skf.split(X_train_processed,y_train):
        X_fold_train=X_train_processed.iloc[train_idx]
        X_fold_valid=X_train_processed.iloc[valid_idx]
        y_fold_train=y_train.iloc[train_idx]
        y_fold_valid=y_train.iloc[valid_idx]

        random_forest_tune.fit(X_fold_train,y_fold_train.values.ravel())

        y_fold_pred=random_forest_tune.predict(X_fold_valid)

        score=f1_score(y_fold_valid,y_fold_pred)

        cv_f1_score.append(score)

    return np.mean(cv_f1_score)

In [174]:
study=optuna.create_study(direction='maximize')

study.optimize(objective,n_trials=50)

[I 2026-07-02 00:38:37,309] A new study created in memory with name: no-name-3eff741b-9269-4ee1-91d7-97bb549d9d1e
[I 2026-07-02 00:38:44,393] Trial 0 finished with value: 0.2286814844667629 and parameters: {'n_estimators': 50, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 0 with value: 0.2286814844667629.
[I 2026-07-02 00:39:44,458] Trial 1 finished with value: 0.2135621842012306 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.2286814844667629.
[I 2026-07-02 00:40:19,813] Trial 2 finished with value: 0.2313450975974894 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 2 with value: 0.2313450975974894.
[I 2026-07-02 00:41:24,167] Trial 3 finished with value: 0.23073045513703327 and parameters: {'n_estimators': 450, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 2 with value: 0.2313450975974894.
[I 2026-07-02 00:42:15,091] Trial 4 finished with value: 0.22297305943444506 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 19, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.2313450975974894.
[I 2026-07-02 00:43:10,572] Trial 5 finished with value: 0.21769673614983698 and parameters: {'n_estimators': 350, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 2 with value: 0.2313450975974894.
[I 2026-07-02 00:44:36,131] Trial 6 finished with value: 0.2172558947993279 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.2313450975974894.
[I 2026-07-02 00:46:44,084] Trial 7 finished with value: 0.22269094710810214 and parameters: {'n_estimators': 450, 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 2 with value: 0.2313450975974894.
[I 2026-07-02 00:49:11,799] Trial 8 finished with value: 0.22625535792471813 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 2 with value: 0.2313450975974894.
[I 2026-07-02 00:50:16,074] Trial 9 finished with value: 0.23160248906265749 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:50:24,360] Trial 10 finished with value: 0.21226203539648295 and parameters: {'n_estimators': 50, 'max_depth': 19, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:50:42,416] Trial 11 finished with value: 0.22034843132884632 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:51:02,667] Trial 12 finished with value: 0.2311950812713374 and parameters: {'n_estimators': 150, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:51:32,964] Trial 13 finished with value: 0.23053794157306876 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:51:58,084] Trial 14 finished with value: 0.22146970809839944 and parameters: {'n_estimators': 150, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:53:38,931] Trial 15 finished with value: 0.22696535559813302 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:54:53,316] Trial 16 finished with value: 0.23143128643723215 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:56:05,062] Trial 17 finished with value: 0.2237843845225782 and parameters: {'n_estimators': 500, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:58:24,427] Trial 18 finished with value: 0.2275788114565756 and parameters: {'n_estimators': 450, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 00:59:17,237] Trial 19 finished with value: 0.22848327284753464 and parameters: {'n_estimators': 400, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 01:00:02,731] Trial 20 finished with value: 0.22039756693317095 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 9 with value: 0.23160248906265749.
[I 2026-07-02 01:00:57,364] Trial 21 finished with value: 0.23177058312674945 and parameters: {'n_estimators': 400, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:01:58,636] Trial 22 finished with value: 0.23177058312674945 and parameters: {'n_estimators': 400, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:02:53,410] Trial 23 finished with value: 0.2312286528198622 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 17, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:03:50,169] Trial 24 finished with value: 0.22558692911773154 and parameters: {'n_estimators': 350, 'max_depth': 17, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:04:25,291] Trial 25 finished with value: 0.2251222449047286 and parameters: {'n_estimators': 350, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:05:31,643] Trial 26 finished with value: 0.22887510466219854 and parameters: {'n_estimators': 450, 'max_depth': 13, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:06:29,798] Trial 27 finished with value: 0.22675532088426859 and parameters: {'n_estimators': 400, 'max_depth': 17, 'min_samples_split': 17, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:07:16,258] Trial 28 finished with value: 0.2314787838317902 and parameters: {'n_estimators': 350, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:09:38,203] Trial 29 finished with value: 0.22747787055311425 and parameters: {'n_estimators': 450, 'max_depth': 9, 'min_samples_split': 20, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:10:25,535] Trial 30 finished with value: 0.2250822582173086 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:11:14,217] Trial 31 finished with value: 0.2314787838317902 and parameters: {'n_estimators': 350, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:12:00,233] Trial 32 finished with value: 0.22949089651161092 and parameters: {'n_estimators': 350, 'max_depth': 9, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:12:41,094] Trial 33 finished with value: 0.23105138254636928 and parameters: {'n_estimators': 250, 'max_depth': 13, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:13:25,887] Trial 34 finished with value: 0.2317094378896894 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:14:02,680] Trial 35 finished with value: 0.22824368985419213 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:14:41,011] Trial 36 finished with value: 0.2317094378896894 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:15:26,240] Trial 37 finished with value: 0.23167720430622163 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:16:10,145] Trial 38 finished with value: 0.22966000413075705 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:16:51,349] Trial 39 finished with value: 0.23167720430622163 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 14, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:17:25,398] Trial 40 finished with value: 0.2316447071382716 and parameters: {'n_estimators': 250, 'max_depth': 11, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:18:14,762] Trial 41 finished with value: 0.23167720430622163 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:19:09,461] Trial 42 finished with value: 0.23118164477410907 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:19:43,817] Trial 43 finished with value: 0.22943118065249526 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:20:21,052] Trial 44 finished with value: 0.2317094378896894 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:21:11,052] Trial 45 finished with value: 0.23161360295113625 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:21:53,346] Trial 46 finished with value: 0.22940117478777516 and parameters: {'n_estimators': 350, 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:23:18,769] Trial 47 finished with value: 0.23001215381012657 and parameters: {'n_estimators': 250, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:23:56,045] Trial 48 finished with value: 0.2317094378896894 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.
[I 2026-07-02 01:24:38,255] Trial 49 finished with value: 0.22902666198477117 and parameters: {'n_estimators': 350, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.23177058312674945.

In [175]:
study.best_params

{'n_estimators': 400,
 'max_depth': 13,
 'min_samples_split': 15,
 'min_samples_leaf': 9,
 'max_features': 'log2'}

In [176]:
study.best_value

0.23177058312674945

In [177]:
study.best_trial

FrozenTrial(number=21, state=<TrialState.COMPLETE: 1>, values=[0.23177058312674945], datetime_start=datetime.datetime(2026, 7, 2, 1, 0, 2, 731712), datetime_complete=datetime.datetime(2026, 7, 2, 1, 0, 57, 364605), params={'n_estimators': 400, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': 'log2'}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_estimators': IntDistribution(high=500, log=False, low=50, step=50), 'max_depth': IntDistribution(high=19, log=False, low=5, step=2), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=10, log=False, low=1, step=1), 'max_features': CategoricalDistribution(choices=('sqrt', 'log2', None))}, trial_id=21, value=None)

In [178]:
def objective(trial):
    n_estimators=trial.suggest_int('n_estimators',50,500,step=50)
    max_depth=trial.suggest_int('max_depth',5,19,step=2)
    min_samples_split=trial.suggest_int('min_samples_split',2,20,step=1)
    min_samples_leaf=trial.suggest_int('min_samples_leaf',1,10,step=1)
    max_features=trial.suggest_categorical('max_features',['sqrt','log2',None])
    
    random_forest_tune=RandomForestClassifier(n_estimators=n_estimators,max_depth=max_depth,
                                              min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf,
                                              max_features=max_features,class_weight='balanced',
                                              bootstrap=True,criterion='gini',random_state=42,n_jobs=-1)
    
    skf = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
    cv_scores=cross_val_score(estimator=random_forest_tune,X=X_train_processed,y=y_train.values.ravel(),cv=skf,scoring='f1')
    return cv_scores.mean()

In [179]:
study1=optuna.create_study(direction='maximize')

study1.optimize(objective,n_trials=50)

[I 2026-07-02 01:24:38,575] A new study created in memory with name: no-name-13e4af30-0305-4bd8-bf3c-638a4e83ecb2
[I 2026-07-02 01:25:03,766] Trial 0 finished with value: 0.2300532931319485 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 0.2300532931319485.
[I 2026-07-02 01:25:35,658] Trial 1 finished with value: 0.22788008904197246 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 0 with value: 0.2300532931319485.
[I 2026-07-02 01:27:35,686] Trial 2 finished with value: 0.22676239338753654 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 0 with value: 0.2300532931319485.
[I 2026-07-02 01:27:42,173] Trial 3 finished with value: 0.23015439229271029 and parameters: {'n_estimators': 50, 'max_depth': 13, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.23015439229271029.
[I 2026-07-02 01:28:01,189] Trial 4 finished with value: 0.22661247510256777 and parameters: {'n_estimators': 150, 'max_depth': 17, 'min_samples_split': 13, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.23015439229271029.
[I 2026-07-02 01:29:30,158] Trial 5 finished with value: 0.2225533315414609 and parameters: {'n_estimators': 350, 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 3 with value: 0.23015439229271029.
[I 2026-07-02 01:29:41,087] Trial 6 finished with value: 0.22416856169343333 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.23015439229271029.
[I 2026-07-02 01:31:09,666] Trial 7 finished with value: 0.22259595928626436 and parameters: {'n_estimators': 350, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 3 with value: 0.23015439229271029.
[I 2026-07-02 01:31:57,819] Trial 8 finished with value: 0.22958664873803825 and parameters: {'n_estimators': 450, 'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 3 with value: 0.23015439229271029.
[I 2026-07-02 01:32:10,767] Trial 9 finished with value: 0.2207529433683344 and parameters: {'n_estimators': 150, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 3 with value: 0.23015439229271029.
[I 2026-07-02 01:33:26,157] Trial 10 finished with value: 0.22318121966020343 and parameters: {'n_estimators': 500, 'max_depth': 19, 'min_samples_split': 19, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.23015439229271029.
[I 2026-07-02 01:33:58,253] Trial 11 finished with value: 0.23060638762019475 and parameters: {'n_estimators': 250, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 11 with value: 0.23060638762019475.
[I 2026-07-02 01:34:39,715] Trial 12 finished with value: 0.22784395939494012 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 11 with value: 0.23060638762019475.
[I 2026-07-02 01:34:46,718] Trial 13 finished with value: 0.22954522260356286 and parameters: {'n_estimators': 50, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.23060638762019475.
[I 2026-07-02 01:35:21,358] Trial 14 finished with value: 0.2292598052607898 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.23060638762019475.
[I 2026-07-02 01:36:05,734] Trial 15 finished with value: 0.22993931193530134 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 11 with value: 0.23060638762019475.
[I 2026-07-02 01:36:13,219] Trial 16 finished with value: 0.22643202970574766 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.23060638762019475.
[I 2026-07-02 01:36:38,215] Trial 17 finished with value: 0.23089875469874013 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 17 with value: 0.23089875469874013.
[I 2026-07-02 01:37:14,515] Trial 18 finished with value: 0.20213670370590514 and parameters: {'n_estimators': 250, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 17 with value: 0.23089875469874013.
[I 2026-07-02 01:37:40,275] Trial 19 finished with value: 0.2310759131416012 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:38:00,490] Trial 20 finished with value: 0.2308065088349685 and parameters: {'n_estimators': 150, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:38:20,893] Trial 21 finished with value: 0.2308065088349685 and parameters: {'n_estimators': 150, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:38:43,604] Trial 22 finished with value: 0.2292759377470536 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:39:07,180] Trial 23 finished with value: 0.23041747322230677 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:39:18,700] Trial 24 finished with value: 0.23096300578345047 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:39:29,034] Trial 25 finished with value: 0.2288928704163721 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:40:08,322] Trial 26 finished with value: 0.2257654273343208 and parameters: {'n_estimators': 300, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:40:34,764] Trial 27 finished with value: 0.23089875469874013 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:40:49,284] Trial 28 finished with value: 0.2193579125765031 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:41:27,079] Trial 29 finished with value: 0.23107483389562247 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:42:03,905] Trial 30 finished with value: 0.23107483389562247 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:42:36,911] Trial 31 finished with value: 0.23107483389562247 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:43:11,866] Trial 32 finished with value: 0.23107483389562247 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:44:59,217] Trial 33 finished with value: 0.22694987227054306 and parameters: {'n_estimators': 350, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:45:41,146] Trial 34 finished with value: 0.2292568372861433 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 19 with value: 0.2310759131416012.
[I 2026-07-02 01:46:26,599] Trial 35 finished with value: 0.23166534094282953 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:48:45,106] Trial 36 finished with value: 0.2289382866100313 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:49:27,114] Trial 37 finished with value: 0.22482885956511747 and parameters: {'n_estimators': 450, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:51:13,337] Trial 38 finished with value: 0.22743503645258484 and parameters: {'n_estimators': 350, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': None}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:52:06,314] Trial 39 finished with value: 0.22856743420537656 and parameters: {'n_estimators': 450, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:53:06,106] Trial 40 finished with value: 0.23093806942784229 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:53:44,584] Trial 41 finished with value: 0.23107483389562247 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:54:24,512] Trial 42 finished with value: 0.23163387289072412 and parameters: {'n_estimators': 350, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:55:01,101] Trial 43 finished with value: 0.22949089651161092 and parameters: {'n_estimators': 350, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:55:54,818] Trial 44 finished with value: 0.23023846272596082 and parameters: {'n_estimators': 400, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:56:33,706] Trial 45 finished with value: 0.22932407474223188 and parameters: {'n_estimators': 350, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:58:27,353] Trial 46 finished with value: 0.2227778118709947 and parameters: {'n_estimators': 450, 'max_depth': 7, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:59:02,527] Trial 47 finished with value: 0.22054764775617733 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 01:59:33,496] Trial 48 finished with value: 0.2300379074677139 and parameters: {'n_estimators': 250, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.
[I 2026-07-02 02:00:06,185] Trial 49 finished with value: 0.23156517627229362 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 35 with value: 0.23166534094282953.

In [180]:
study1.best_params

{'n_estimators': 400,
 'max_depth': 11,
 'min_samples_split': 5,
 'min_samples_leaf': 8,
 'max_features': 'log2'}

In [181]:
study1.best_value

0.23166534094282953

In [182]:
study1.best_trial

FrozenTrial(number=35, state=<TrialState.COMPLETE: 1>, values=[0.23166534094282953], datetime_start=datetime.datetime(2026, 7, 2, 1, 45, 41, 148106), datetime_complete=datetime.datetime(2026, 7, 2, 1, 46, 26, 599810), params={'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'log2'}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_estimators': IntDistribution(high=500, log=False, low=50, step=50), 'max_depth': IntDistribution(high=19, log=False, low=5, step=2), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=10, log=False, low=1, step=1), 'max_features': CategoricalDistribution(choices=('sqrt', 'log2', None))}, trial_id=35, value=None)

In [183]:
final_random_forest=RandomForestClassifier(**study1.best_params,bootstrap=True,class_weight='balanced',criterion='gini',random_state=42,n_jobs=-1)

In [184]:
final_random_forest.fit(X_train_processed,y_train.values.ravel())

RandomForestClassifier(class_weight='balanced', max_depth=11,
                       max_features='log2', min_samples_leaf=8,
                       min_samples_split=5, n_estimators=400, n_jobs=-1,
                       random_state=42)

In [185]:
final_y_pred_rf=final_random_forest.predict(X_test_processed)

In [186]:
final_y_proba_rf=final_random_forest.predict_proba(X_test_processed)[:,1]

In [187]:
final_metrics_rf=evaluate_model('Random Forest',y_true=y_test.values.ravel(),y_pred=final_y_pred_rf,y_prob=final_y_proba_rf)
final_metrics_rf

Model          : Random Forest
Accuracy       : 0.6396993966764281
Precision      : 0.09589570255915017
Recall         : 0.5387954422137818
F1 Score       : 0.16281357599606494
ROC-AUC        : 0.6457118930373982
Test Samples   : 28343

Confusion Matrix
[[17138  9362]
 [  850   993]]

Classification Report

              precision    recall  f1-score       support
0              0.952746  0.646717  0.770455  26500.000000
1              0.095896  0.538795  0.162814   1843.000000
accuracy       0.639699  0.639699  0.639699      0.639699
macro avg      0.524321  0.592756  0.466634  28343.000000
weighted avg   0.897030  0.639699  0.730943  28343.000000

In [188]:
y_train.value_counts()

made_sla
0           105997
1             7372
Name: count, dtype: int64

## Threshold Optimization

Most classification models predict probabilities instead of directly predicting class labels.

By default, Scikit-Learn classifies an observation as the positive class when the predicted probability is greater than or equal to **0.50**.

However, the default threshold may not align with the business objective.

For SLA breach prediction, the cost of missing an actual SLA breach (False Negative) is generally higher than investigating an additional incident (False Positive). Therefore, different probability thresholds are evaluated to identify the threshold that provides the best trade-off between Precision, Recall, and F1 Score.

The threshold that best aligns with the business objective will be selected for the final prediction.

In [189]:
%store -r y_test
def evaluate_thresholds(y_true,y_prob,thresholds=np.arange(0.1,1.0,0.1)):
    """
        Evaluate multiple probability thresholds for binary classification.

        Parameters
        ----------
        y_true : array-like
            Actual target labels.

        y_prob : array-like
            Predicted probabilities for the positive class.

        thresholds : iterable
            Probability thresholds to evaluate.

            Returns
            -------
            pandas.DataFrame
            DataFrame containing Precision, Recall and F1 Score for each threshold.
            """  
    results=[]

    for threshold in thresholds:
        y_pred=(y_prob>=threshold).astype(int)
        precision=precision_score(y_true=y_true,y_pred=y_pred,zero_division=0)
        recall=recall_score(y_true=y_true,y_pred=y_pred,zero_division=0)
        f1=f1_score(y_true=y_true,y_pred=y_pred,zero_division=0)

        results.append({'Threshold':threshold,
                        'Precision':precision,
                        'Recall':recall,
                        'F1 Score':f1})

    return pd.DataFrame(results)
        
threshold_df = evaluate_thresholds(
    y_true=y_test,
    y_prob=final_y_proba_rf
)

threshold_df

   Threshold  Precision    Recall  F1 Score
0        0.1   0.079118  0.964189  0.146237
1        0.2   0.082700  0.855670  0.150822
2        0.3   0.086113  0.763429  0.154768
3        0.4   0.090969  0.676614  0.160376
4        0.5   0.095896  0.538795  0.162814
5        0.6   0.102223  0.396636  0.162553
6        0.7   0.105263  0.162778  0.127850
7        0.8   0.190909  0.011394  0.021505
8        0.9   1.000000  0.000543  0.001085

# Model Analysis and Business Optimization

After training the final Random Forest model, the remaining analyses use the predicted probabilities generated by the trained model.

The model is **not retrained** during these analyses. Instead, the predicted probabilities are reused to perform:

- Threshold Optimization
- Precision-Recall Trade-off Analysis
- ROC Analysis
- Business Metric Evaluation
- Model Explainability (SHAP)

This approach is computationally efficient and reflects how trained models are evaluated in production environments.

In [190]:
print(final_random_forest.classes_)

[0 1]

In [203]:
final_random_forest.predict_proba(X_test_processed)[:,1]

array([0.04058561, 0.59716051, 0.14536754, ..., 0.4223163 , 0.0227934 ,
       0.70183151], shape=(28343,))

In [192]:
print(y_test.value_counts())

made_sla
0    26500
1     1843
Name: count, dtype: int64

In [193]:
from sklearn.metrics import confusion_matrix

threshold = 0.5
y_pred = (final_y_proba_rf >= threshold).astype(int)

print(confusion_matrix(y_test, y_pred))

[[17138  9362]
 [  850   993]]

In [194]:
print(confusion_matrix(y_test, final_y_pred_rf))

[[17138  9362]
 [  850   993]]

In [195]:
print(np.array_equal(y_pred, final_y_pred_rf))

True

## Threshold Analysis

The default classification threshold of most binary classifiers is **0.50**.

However, different probability thresholds can significantly affect the trade-off between **Precision** and **Recall**.

To understand this trade-off, Precision, Recall, and F1 Score are evaluated across multiple thresholds. This helps identify the operating threshold that best aligns with the business objective of predicting SLA breaches.