# Model Training

Objective:
Build a machine learning pipeline capable of predicting SLA breaches at incident creation time.

The modeling phase includes:

- Preprocessing Pipeline
- Missing Value Handling
- Encoding
- Class Imbalance Handling
- Model Training
- Cross Validation
- Hyperparameter Tuning
- Model Selection

# Import Libraries

In [272]:
import pandas as pd
import numpy as np
import calendar
from pandas.api.types import is_object_dtype, is_string_dtype
from sklearn.utils.validation import check_is_fitted
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder,TargetEncoder,FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,roc_auc_score
from sklearn.model_selection import cross_val_score

# Load Processed Data

In [273]:
X_train=pd.read_csv('../../data/processed/X_train.csv')
X_test=pd.read_csv('../../data/processed/X_test.csv')
y_train=pd.read_csv('../../data/processed/y_train.csv')
y_test=pd.read_csv('../../data/processed/y_test.csv')

# Feature Groups

| Feature Group      | Features                                                        |
| ------------------ | --------------------------------------------------------------- |
| Frequency Encoding | category, subcategory, assignment_group, assigned_to, opened_by |
| Target Encoding    | caller_id, location, u_symptom, contact_type                    |
| Ordinal Encoding   | impact, urgency, priority                                       |
| Numerical          | Hour                                                            |
| Calendar Features  | Month, Day_of_week                                              |
                                          |

## Preprocessing Pipeline Design

### Traditional ML Pipeline

Missing Value Replacement
        ↓
Ordinal Encoding
        ↓
Frequency Encoding
        ↓
Target Encoding
        ↓
Model

### CatBoost Pipeline

Missing Value Replacement
        ↓
Ordinal Encoding
        ↓
Native Categorical Handling
        ↓
CatBoost

# Custom Transformers

In [274]:

replacement={
    'location': 'Unknown_location',
    'category':'Unknown_category',
    'subcategory':'Unknown_subcategory',
    'u_symptom':'Unknown_symptom',
    'assignment_group':'Unknown_assignment_group',
    'assigned_to':'Unknown_assigned_to',
    'caller_id': 'Unknown_caller_id',
    'opened_by':'Unknown_opened_by'
}

nested_replacement={col: {'?':val} for col, val in replacement.items()}

def replace_missing_value(X):
    X_copy=X.copy()
    return X_copy.replace(nested_replacement)

missing_value_imputer = FunctionTransformer(replace_missing_value)

missing_values_pipeline=Pipeline([('impute_missing_value',missing_value_imputer)])

In [275]:
from sklearn.base import BaseEstimator, TransformerMixin

class BusinessMissingValueTransformer(BaseEstimator, TransformerMixin):

    def __init__(self):
        self.replacement = {
            'location': 'Unknown_location',
            'category': 'Unknown_category',
            'subcategory': 'Unknown_subcategory',
            'u_symptom': 'Unknown_symptom',
            'assignment_group': 'Unknown_assignment_group',
            'assigned_to': 'Unknown_assigned_to',
            'caller_id': 'Unknown_caller_id',
            'opened_by': 'Unknown_opened_by'
        }

        self.missing_tokens = ['?', 'NA', 'N/A', None]

    def fit(self, X, y=None):

        missing_cols = []

        for col in self.replacement.keys():
            if col not in X.columns:
                missing_cols.append(col)

        if missing_cols:
            raise ValueError(
                f"Required missing columns are: {missing_cols}"
            )

        return self

    def transform(self, X):

        X_copy = X.copy()

        for col, replacement_value in self.replacement.items():

            X_copy[col] = X_copy[col].replace(
                self.missing_tokens,
                replacement_value
            )

        return X_copy

In [276]:
missing_transformer = BusinessMissingValueTransformer()

missing_transformer.fit(X_train)

X_train_transformed = missing_transformer.transform(X_train)

In [277]:
(X_train_transformed[
    ['location','category','subcategory',
     'u_symptom','assignment_group',
     'assigned_to','caller_id','opened_by']
].isin(['?','NA','N/A']).sum())

location            0
category            0
subcategory         0
u_symptom           0
assignment_group    0
assigned_to         0
caller_id           0
opened_by           0
dtype: int64

In [278]:
X_train['priority'].value_counts()

priority
3 - Moderate    105915
4 - Low           3240
2 - High          2370
1 - Critical      1844
Name: count, dtype: int64

In [279]:
# Ordinal Transformer

class OrdinalTransformer(BaseEstimator,TransformerMixin):
    """
    Custom transformer to perform business-rule-based ordinal encoding.

    Features:
    - Validates required columns.
    - Detects unseen categories before transformation.
    - Encodes Impact, Urgency and Priority based on predefined business mappings.
    - Raises descriptive exceptions when unexpected categories are encountered.
    - Compatible with Scikit-Learn Pipelines.
    """
    def __init__(self,ordinal_mappings=None):
        if ordinal_mappings is None:
            self.ordinal_mappings={
                'impact':{
                    '3 - Low':1,
                    '2 - Medium':2,
                    '1 - High':3
                },
                'urgency':{
                    '3 - Low':1,
                    '2 - Medium':2,
                    '1 - High':3
                },
                'priority':{
                    '4 - Low':1,
                    '3 - Moderate':2,
                    '2 - High':3,
                    '1 - Critical':4
                }
            }
        else:
            """To build this as a reusable package, I am inject the mappings through the constructor with a default configuration."""
            self.ordinal_mappings = ordinal_mappings ## using this line we can use this transformer in any project

    def _validate_input(self,X):
         if not isinstance(X,pd.DataFrame):
              raise TypeError(f"Expected a pandas DataFrame, but got {type(X).__name__}")
    
    def _validate_columns(self,X):
        """Helper method to ensure all expected mapping columns exist in the dataset."""
        missing_columns=[col for col in self.ordinal_mappings.keys() if col not in X.columns]
        if missing_columns:
            raise ValueError(f"Required missing columns are :{missing_columns}") 
        

    def fit(self,X,y=None):
        """
        Validate that all required ordinal columns are present.
        """
        self._validate_input(X)
        self._validate_columns(X)
        return self

    def transform(self,X):
        """
        Validate ordinal values and apply business-rule-based encoding.
        """
        self._validate_input(X)
        self._validate_columns(X)
        
        X_copy=X.copy()
        invalid_values={}

        for col,mapping in self.ordinal_mappings.items():
            diff=set(X_copy[col].unique()) - set(mapping.keys())
            if diff:
                 invalid_values[col]=diff
        
        if invalid_values:
            raise ValueError(f"Unknown categorical values found during transformation: {invalid_values}")
        
        for col,value in self.ordinal_mappings.items():
            X_copy[col]=X_copy[col].map(value)
            
        return X_copy
        
ordinal_transformer = OrdinalTransformer()

X_train_ordinal = ordinal_transformer.fit_transform(X_train)
X_train_ordinal[['impact','urgency','priority']]

        impact  urgency  priority
0            2        2         2
1            2        2         2
2            2        2         2
3            2        2         2
4            2        2         2
...        ...      ...       ...
113364       2        2         2
113365       2        2         2
113366       2        2         2
113367       2        2         2
113368       2        2         2

[113369 rows x 3 columns]

In [280]:
#Frequency Encoder

class FrequencyEncoder(BaseEstimator,TransformerMixin):
    """
    Custom transformer to perform frequency encoding.

    Features:
        - Learns normalized frequencies from training data.
        - Encodes configured high-cardinality categorical features.
        - Handles unseen categories using a configurable unknown_value.
        - Compatible with Scikit-Learn Pipelines.
    """
    def __init__(self,frequency_columns=None,unknown_value=0.0):
        if frequency_columns is None:
            self.frequency_columns=[
            'category',
            'subcategory',
            'assignment_group',
            'assigned_to',
            'opened_by'
            ]
        else:
            self.frequency_columns=frequency_columns

        self.frequency_mappings={}
        self.unknown_value = unknown_value
    
    def _validate_input(self,X):
        if not isinstance(X,pd.DataFrame):
              raise TypeError(f"Expected a pandas DataFrame, but got {type(X).__name__}")
    
    def _validate_columns(self,X):
        missing_columns=[col for col in self.frequency_columns if col not in X.columns]
        if missing_columns:
            raise ValueError(f"Required missing columns are :{missing_columns}")
        
    def fit(self,X,y=None):
        self._validate_input(X)
        self._validate_columns(X)
        self.frequency_mappings={
          col:X[col].value_counts(normalize=True).to_dict()  for col in self.frequency_columns
        }
        
        return self

    def transform(self,X,y=None):
        self._validate_input(X)
        self._validate_columns(X)
        X_copy=X.copy()

        if not self.frequency_mappings:
            raise ValueError(
                "FrequencyEncoder has not been fitted yet. "
                "Call fit() before transform()."
                )
        
        for col, mapping in self.frequency_mappings.items():
            X_copy[col] = X_copy[col].map(mapping)

            X_copy[col] = X_copy[col].fillna(self.unknown_value)
            
        return X_copy


encoder = FrequencyEncoder()

encoder.fit(X_train)

X_train_encoded = encoder.transform(X_train)
X_train_encoded

       contact_type      location  category  ...  Hour Day_of_week  Month
0             Phone   Location 51  0.113276  ...    15      Friday    May
1             Phone  Location 143  0.130538  ...    21    Thursday  March
2             Phone  Location 143  0.045833  ...     8      Monday    May
3             Phone  Location 143  0.036421  ...    16     Tuesday    May
4             Phone  Location 143  0.051028  ...    20     Tuesday  April
...             ...           ...       ...  ...   ...         ...    ...
113364        Phone  Location 143  0.039164  ...     9      Friday    May
113365        Phone   Location 38  0.093862  ...    10   Wednesday  March
113366        Phone  Location 204  0.130538  ...    12      Monday  March
113367        Phone  Location 143  0.051972  ...     7      Sunday    May
113368        Phone  Location 204  0.112165  ...    10     Tuesday  March

[113369 rows x 15 columns]

In [281]:
encoder = FrequencyEncoder(unknown_value=0.0)
encoder.fit(X_train)

# Clean naming convention to keep track of splits
X_test_encoded = encoder.transform(X_test)
X_test_encoded

      contact_type      location  category  ...  Hour Day_of_week  Month
0            Phone  Location 188  0.093862  ...     1      Sunday  April
1            Phone  Location 204  0.028103  ...    14     Tuesday    May
2            Phone   Location 37  0.093862  ...    16   Wednesday  March
3            Phone   Location 56  0.046159  ...     8      Monday  April
4            Phone  Location 204  0.051028  ...     8     Tuesday  April
...            ...           ...       ...  ...   ...         ...    ...
28338        Phone  Location 204  0.055456  ...    16      Monday  March
28339        Phone  Location 143  0.113276  ...     9      Monday  March
28340        Phone  Location 108  0.130538  ...     8      Friday    May
28341        Phone   Location 51  0.051972  ...     9      Friday    May
28342        Phone   Location 55  0.051972  ...     9      Monday  March

[28343 rows x 15 columns]

In [282]:
# Filters the DataFrame to only your processed columns and checks for 0.0
zero_counts = (X_test_encoded[encoder.frequency_columns] == 0.0).sum()

print("Count of 0.0 values per column:")
print(zero_counts)

Count of 0.0 values per column:
category            0
subcategory         2
assignment_group    0
assigned_to         3
opened_by           3
dtype: int64

In [283]:
class TargetEncoder(BaseEstimator, TransformerMixin):
    """Custom transformer to perform target encoding with additive smoothing.

    This encoder replaces categorical values with the smoothed mean of the 
    target variable for that specific category. It balances the local category 
    mean against the global target mean to mitigate overfitting in high-cardinality 
    features or small sample sizes.

    Parameters
    ----------
    target_columns : list of str, default=None
        The columns in the input DataFrame to be target encoded. If None, 
        defaults to ['caller_id', 'location', 'u_symptom', 'contact_type'].
    target_column : str, default='made_sla'
        The column name of the target variable used to search inside `y` if 
        it is passed as a pandas DataFrame.
    smoothing : int or float, default=10
        The smoothing factor (m-estimate constant). Higher values pull category 
        means closer to the global mean, acting as a stronger regularizer.

    Attributes
    ----------
    target_mappings : dict
        Nested dictionary mapping feature names to dictionaries of encoded category values.
    global_mean : float
        The overall mean of the target variable across the entire training set.
    n_features_in_ : tuple
        The shape dimensions of the feature matrix seen during `fit`.
    """
    
    def __init__(self, target_columns=None, target_column='made_sla', smoothing=10):
        if target_columns is None:
            self.target_columns = ['caller_id', 'location', 'u_symptom', 'contact_type']
        else:
            self.target_columns = target_columns
            
        self.target_column = target_column
        self.smoothing = smoothing
        self.target_mappings = {}
        self.global_mean = None

    def _validate_X(self, X):
        """Validates input structural data type for the feature matrix X."""
        if not isinstance(X, pd.DataFrame):
            raise TypeError(f"Expected X to be a pandas DataFrame, but got {type(X).__name__}")

    def _validate_y(self, y):
        """Validates input structural data types, dimensions, and naming for the target vector y."""
        if not isinstance(y, (pd.Series, pd.DataFrame, np.ndarray)):
            raise TypeError(f"Expected y to be a Series, DataFrame, or array, but got {type(y).__name__}")
        
        if isinstance(y, pd.DataFrame) and self.target_column not in y.columns:
            raise ValueError(f"The target column '{self.target_column}' is missing from the target DataFrame.")
            
        if isinstance(y, np.ndarray) and y.ndim != 1:
            raise ValueError(f"Expected y to be a 1D array, but got a {y.ndim}D array instead.")

    def _validate_columns(self, X):
        """Verifies that all specified feature columns exist in the DataFrame."""
        missing_columns = [col for col in self.target_columns if col not in X.columns]
        if missing_columns:    
            raise ValueError(f"Required missing columns are: {missing_columns}")

    def _compute_smoothed_mean(self, group_stats):
        """Calculates the smoothed target value using the explicit local variables layout."""
        numerator = (group_stats['count'] * group_stats['mean']) + (self.smoothing * self.global_mean)
        denominator = group_stats['count'] + self.smoothing
        return numerator / denominator

    def fit(self, X, y):
        """Fit the target encoder by calculating smoothed category means.

        Parameters
        ----------
        X : pandas.DataFrame
            The feature matrix containing columns to encode.
        y : pandas.Series, pandas.DataFrame, or numpy.ndarray
            The target vector.

        Returns
        -------
        self : object
            Returns the instance itself.
        """
        self._validate_X(X)
        self._validate_y(y)
        self._validate_columns(X)
        
        self.n_features_in_ = X.shape[1]
        
        if isinstance(y, pd.DataFrame):
            y_series = y[self.target_column]
        elif isinstance(y, pd.Series):
            y_series = y
        else:
            y_series = pd.Series(y, index=X.index)

        self.global_mean = y_series.mean()
        self.target_mappings = {}

        for col in self.target_columns:
            encoding_df = pd.concat([X[col], y_series.rename(self.target_column)], axis=1)
            group_stats = encoding_df.groupby(col)[self.target_column].agg(['mean', 'count'])

            group_stats['smoothed'] = self._compute_smoothed_mean(group_stats)
            self.target_mappings[col] = group_stats['smoothed'].to_dict()
             
        return self
    
    def transform(self, X):
        """Transform the categorical columns using the learned target mappings.

        Unseen categories encountered during testing will be imputed with 
        the global training mean.

        Parameters
        ----------
        X : pandas.DataFrame
            The feature matrix to transform.

        Returns
        -------
        X_transformed : pandas.DataFrame
            The transformed DataFrame with numerical target-encoded features.
        """
        self._validate_X(X)
        self._validate_columns(X)
        
        check_is_fitted(self, "n_features_in_")

        X_transformed = X.copy()
        for col, mapping in self.target_mappings.items():
            X_transformed[col] = (X_transformed[col].map(mapping).fillna(self.global_mean))
    

        return X_transformed
                 

    def get_feature_names_out(self, input_features=None):
        """Returns feature names out for Scikit-Learn pipeline support."""
        if input_features is None:
            return np.array(self.target_columns)
        return np.array(input_features)

In [284]:
target_encoder=TargetEncoder().fit(X_train,y_train)

In [285]:
target_encoder.transform(X_test)

       contact_type  location     category  ... Hour  Day_of_week  Month
0          0.935146  0.988166  Category 46  ...    1       Sunday  April
1          0.935146  0.927769  Category 34  ...   14      Tuesday    May
2          0.935146  0.911855  Category 46  ...   16    Wednesday  March
3          0.935146  0.927777  Category 57  ...    8       Monday  April
4          0.935146  0.927769  Category 32  ...    8      Tuesday  April
...             ...       ...          ...  ...  ...          ...    ...
28338      0.935146  0.927769  Category 23  ...   16       Monday  March
28339      0.935146  0.930394  Category 42  ...    9       Monday  March
28340      0.935146  0.942683  Category 26  ...    8       Friday    May
28341      0.935146  0.933127   Category 9  ...    9       Friday    May
28342      0.935146  0.936399   Category 9  ...    9       Monday  March

[28343 rows x 15 columns]

In [286]:
X_train[['Hour', 'Month', 'Day_of_week']].dtypes

Hour           int64
Month            str
Day_of_week      str
dtype: object

In [287]:
X_train[['Hour', 'Month', 'Day_of_week']].describe()

                Hour
count  113369.000000
mean       11.887579
std         4.016466
min         0.000000
25%         9.000000
50%        11.000000
75%        15.000000
max        23.000000

In [288]:
X_train[ 'Month'].unique()

<StringArray>
[      'May',     'March',     'April',  'December',  'February',   'October',
    'August',   'January',  'November',      'July', 'September',      'June']
Length: 12, dtype: str

In [289]:
class CyclicEncoder(BaseEstimator, TransformerMixin):
    """
    Parameters
    ----------
        cyclic_columns : dict, default=None
            Dictionary mapping cyclic feature names to their cycle lengths.

        drop_original : bool, default=True
            Whether to remove the original cyclic columns after encoding.

    Attributes
    ----------
        month_mapping : dict
        day_mapping : dict
        n_features_in_ : int
    """
    def __init__(self,cyclic_columns=None,drop_original=True):
        if cyclic_columns is None:
            self.cyclic_columns={
                'Hour':24,
                'Day_of_week':7,
                'Month':12
            }
        else:
            self.cyclic_columns=cyclic_columns

        self.drop_original=drop_original
        self.month_mapping={
            month:idx for idx,month in enumerate(calendar.month_name) if month
            }
        self.day_mapping={ 
            day:idx for idx,day in enumerate(calendar.day_name) if day
            }
        
        self.category_mappings = {
            "Month": self.month_mapping,
            "Day_of_week": self.day_mapping
        }
        
    
    def _validate_input(self,X):
        if not isinstance(X,pd.DataFrame):
            raise TypeError(f"Expected the pandas Dataframe to be, but got: {type(X).__name__} ")
    
    def _validate_columns(self,X):
        missing_columns=[col for col in self.cyclic_columns if col not in X.columns]
        if missing_columns:    
            raise ValueError(f"Required missing columns are: {missing_columns}") 

    def fit(self,X,y=None):
        self._validate_input(X)
        self._validate_columns(X)
        self.n_features_in_ = X.shape[1]
        return self

    def transform(self,X):
        self._validate_input(X)
        self._validate_columns(X)
        check_is_fitted(self, "n_features_in_")
        X_transformed=X.copy()

        for col, mapping in self.category_mappings.items():
            if col in self.cyclic_columns:
                if is_object_dtype(X_transformed[col]) or is_string_dtype(X_transformed[col]):
                    X_transformed[col] = X_transformed[col].map(mapping)

        for col,period in self.cyclic_columns.items():
                        
            numeric_values = pd.to_numeric(X_transformed[col],errors='raise')

            X_transformed[f'{col}_sin']=np.sin((2*np.pi*numeric_values)/period)
            X_transformed[f'{col}_cos']=np.cos((2*np.pi*numeric_values)/period)
            
        if self.drop_original:
            X_transformed=X_transformed.drop(columns=list(self.cyclic_columns.keys()),errors='ignore')

        return X_transformed

In [290]:
cyclic=CyclicEncoder().fit(X_train,y_train)

In [291]:
cyclic.transform(X_test)

      contact_type      location  ... Month_sin     Month_cos
0            Phone  Location 188  ...  0.866025 -5.000000e-01
1            Phone  Location 204  ...  0.500000 -8.660254e-01
2            Phone   Location 37  ...  1.000000  6.123234e-17
3            Phone   Location 56  ...  0.866025 -5.000000e-01
4            Phone  Location 204  ...  0.866025 -5.000000e-01
...            ...           ...  ...       ...           ...
28338        Phone  Location 204  ...  1.000000  6.123234e-17
28339        Phone  Location 143  ...  1.000000  6.123234e-17
28340        Phone  Location 108  ...  0.500000 -8.660254e-01
28341        Phone   Location 51  ...  0.500000 -8.660254e-01
28342        Phone   Location 55  ...  1.000000  6.123234e-17

[28343 rows x 18 columns]

In [292]:
month_mapping={
            month:idx for idx,month in enumerate(calendar.month_name) if month
            }
for col,mapping in month_mapping.items():
    print(col,mapping)

January 1
February 2
March 3
April 4
May 5
June 6
July 7
August 8
September 9
October 10
November 11
December 12

## Modeling Strategy

Baseline Models
- Logistic Regression
- Decision Tree
- Random Forest

Boosting Models
- XGBoost
- LightGBM
- CatBoost

Evaluation Metrics
- Precision
- Recall
- F1 Score
- ROC-AUC
- PR-AUC

Cross Validation
- Stratified K-Fold

Hyperparameter Optimization
- Optuna

# Preprocessing Pipeline

In [293]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (accuracy_score,
                             precision_score,
                             recall_score,
                             f1_score,
                             roc_auc_score,
                             confusion_matrix,
                             classification_report
                        )

In [294]:
preprocessing_pipeline=Pipeline(steps=[
    ("Business_missing",BusinessMissingValueTransformer()),
    ("ordinal_encoding",OrdinalTransformer()),
    ("Frequency_encoding",FrequencyEncoder()),
    ("Target_encoding",TargetEncoder()),
    ("Cyclic_encoding",CyclicEncoder())
])

X_train_processed=preprocessing_pipeline.fit_transform(X_train,y_train)
X_test_processed=preprocessing_pipeline.transform(X_test)

## Preprocessing Pipeline Validation

In [295]:
X_train_processed.shape,X_test_processed.shape

((113369, 18), (28343, 18))

In [296]:
X_train_processed.dtypes,X_test_processed.dtypes

(contact_type        float64
 location            float64
 category            float64
 subcategory         float64
 u_symptom           float64
 assignment_group    float64
 assigned_to         float64
 caller_id           float64
 opened_by           float64
 impact                int64
 urgency               int64
 priority              int64
 Hour_sin            float64
 Hour_cos            float64
 Day_of_week_sin     float64
 Day_of_week_cos     float64
 Month_sin           float64
 Month_cos           float64
 dtype: object,
 contact_type        float64
 location            float64
 category            float64
 subcategory         float64
 u_symptom           float64
 assignment_group    float64
 assigned_to         float64
 caller_id           float64
 opened_by           float64
 impact                int64
 urgency               int64
 priority              int64
 Hour_sin            float64
 Hour_cos            float64
 Day_of_week_sin     float64
 Day_of_week_cos     float64
 Month_sin           float64
 Month_cos           float64
 dtype: object)

In [297]:
X_train_processed.isnull().sum(),X_test_processed.isnull().sum()

(contact_type        0
 location            0
 category            0
 subcategory         0
 u_symptom           0
 assignment_group    0
 assigned_to         0
 caller_id           0
 opened_by           0
 impact              0
 urgency             0
 priority            0
 Hour_sin            0
 Hour_cos            0
 Day_of_week_sin     0
 Day_of_week_cos     0
 Month_sin           0
 Month_cos           0
 dtype: int64,
 contact_type        0
 location            0
 category            0
 subcategory         0
 u_symptom           0
 assignment_group    0
 assigned_to         0
 caller_id           0
 opened_by           0
 impact              0
 urgency             0
 priority            0
 Hour_sin            0
 Hour_cos            0
 Day_of_week_sin     0
 Day_of_week_cos     0
 Month_sin           0
 Month_cos           0
 dtype: int64)

In [298]:
X_train_processed.columns,X_test_processed.columns

(Index(['contact_type', 'location', 'category', 'subcategory', 'u_symptom',
        'assignment_group', 'assigned_to', 'caller_id', 'opened_by', 'impact',
        'urgency', 'priority', 'Hour_sin', 'Hour_cos', 'Day_of_week_sin',
        'Day_of_week_cos', 'Month_sin', 'Month_cos'],
       dtype='str'),
 Index(['contact_type', 'location', 'category', 'subcategory', 'u_symptom',
        'assignment_group', 'assigned_to', 'caller_id', 'opened_by', 'impact',
        'urgency', 'priority', 'Hour_sin', 'Hour_cos', 'Day_of_week_sin',
        'Day_of_week_cos', 'Month_sin', 'Month_cos'],
       dtype='str'))

In [299]:
X_train_processed.columns==X_test_processed.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [300]:
X_train_processed.describe()

        contact_type       location  ...      Month_sin     Month_cos
count  113369.000000  113369.000000  ...  113369.000000  1.133690e+05
mean        0.934976       0.935025  ...       0.810530 -3.748158e-01
std         0.003999       0.014044  ...       0.231835  3.857572e-01
min         0.835214       0.821144  ...      -1.000000 -1.000000e+00
25%         0.935146       0.927769  ...       0.500000 -8.660254e-01
50%         0.935146       0.933127  ...       0.866025 -5.000000e-01
75%         0.935146       0.942683  ...       1.000000  6.123234e-17
max         0.975916       0.988166  ...       1.000000  1.000000e+00

[8 rows x 18 columns]

In [301]:
X_test_processed.describe()

       contact_type      location  ...     Month_sin     Month_cos
count  28343.000000  28343.000000  ...  28343.000000  2.834300e+04
mean       0.934969      0.934997  ...      0.810115 -3.761496e-01
std        0.003973      0.013895  ...      0.231781  3.853686e-01
min        0.835214      0.821144  ...     -1.000000 -1.000000e+00
25%        0.935146      0.927769  ...      0.500000 -8.660254e-01
50%        0.935146      0.933127  ...      0.866025 -5.000000e-01
75%        0.935146      0.942683  ...      1.000000  6.123234e-17
max        0.975916      0.988166  ...      1.000000  1.000000e+00

[8 rows x 18 columns]

In [302]:
print(f"Training Shape : {X_train_processed.shape}")
print(f"Testing Shape  : {X_test_processed.shape}")

print("\nTraining Missing Values")
print(X_train_processed.isna().sum().sum())

print("\nTesting Missing Values")
print(X_test_processed.isna().sum().sum())

print("\nChecking '?' values in Training Data")
print((X_train_processed == '?').sum())

print("\nChecking '?' values in Testing Data")
print((X_test_processed == '?').sum())

Training Shape : (113369, 18)
Testing Shape  : (28343, 18)

Training Missing Values
0

Testing Missing Values
0

Checking '?' values in Training Data
contact_type        0
location            0
category            0
subcategory         0
u_symptom           0
assignment_group    0
assigned_to         0
caller_id           0
opened_by           0
impact              0
urgency             0
priority            0
Hour_sin            0
Hour_cos            0
Day_of_week_sin     0
Day_of_week_cos     0
Month_sin           0
Month_cos           0
dtype: int64

Checking '?' values in Testing Data
contact_type        0
location            0
category            0
subcategory         0
u_symptom           0
assignment_group    0
assigned_to         0
caller_id           0
opened_by           0
impact              0
urgency             0
priority            0
Hour_sin            0
Hour_cos            0
Day_of_week_sin     0
Day_of_week_cos     0
Month_sin           0
Month_cos           0
dtype: int64

In [303]:
logestic_regression=LogisticRegression(class_weight='balanced',random_state=42,max_iter=1000)

In [304]:
y_train_processed=y_train.to_numpy().reshape(-1,)

In [305]:
logestic_regression.fit(X_train_processed,y_train.values.ravel())

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [306]:
y_pred=logestic_regression.predict(X_test_processed)

In [307]:
y_prob = logestic_regression.predict_proba(X_test_processed)[:, 1]

In [308]:
baseline_results = {
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1 Score": f1_score(y_test, y_pred),
    "ROC-AUC": roc_auc_score(y_test, y_prob)
}

for metric, value in baseline_results.items():
    print(f"{metric:<12}: {value:.4f}")

Accuracy    : 0.6564
Precision   : 0.9502
Recall      : 0.6675
F1 Score    : 0.7841
ROC-AUC     : 0.6423

In [309]:
def evaluate_model(model_name,y_true,y_pred,y_prob):
    """
    Evaluate classification model performance.

    Parameters
    ----------
    y_true : array-like
        Actual target values.

    y_pred : array-like
        Predicted class labels.

    y_prob : array-like
        Predicted probabilities for the positive class.

    Returns
    -------
    dict
        Dictionary containing evaluation metrics and reports.
    """
    report_df = pd.DataFrame(classification_report(y_true, y_pred, output_dict=True)).T
    logistic_results={
        "Model":model_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1 Score": f1_score(y_true, y_pred),
        "ROC-AUC": roc_auc_score(y_true, y_prob),
        "Test Samples": len(y_true),
        "Confusion Matrix": confusion_matrix(y_true, y_pred),
        "Classification Report": report_df
    }
    for metric, value in logistic_results.items():
        if metric not in ["Confusion Matrix", "Classification Report"]:
            print(f"{metric:<15}: {value}")
            
    print("\nConfusion Matrix")
    print(logistic_results["Confusion Matrix"])

    print("\nClassification Report")
    display(logistic_results["Classification Report"])

In [310]:
evaluate_model('Logistic Regression',y_true=y_test,y_pred=y_pred,y_prob=y_prob)

Model          : Logistic Regression
Accuracy       : 0.6563878206259041
Precision      : 0.9502014504431909
Recall         : 0.6674716981132075
F1 Score       : 0.7841294469688573
ROC-AUC        : 0.6422709384821712
Test Samples   : 28343

Confusion Matrix
[[  916   927]
 [ 8812 17688]]

Classification Report

              precision    recall  f1-score       support
False          0.094161  0.497016  0.158327   1843.000000
True           0.950201  0.667472  0.784129  26500.000000
accuracy       0.656388  0.656388  0.656388      0.656388
macro avg      0.522181  0.582244  0.471228  28343.000000
weighted avg   0.894538  0.656388  0.743437  28343.000000

In [311]:
decision_tree=DecisionTreeClassifier(criterion='gini',max_depth=10,class_weight='balanced',random_state=42)

In [312]:
decision_tree.fit(X_train_processed,y_train.values.ravel())

DecisionTreeClassifier(class_weight='balanced', max_depth=10, random_state=42)

In [313]:
y_pred_dt=decision_tree.predict(X_test_processed)

In [314]:
y_prob_dt=decision_tree.predict_proba(X_test_processed)[:,1]

In [315]:
evaluate_model('Decision Tree',y_true=y_test,y_pred=y_pred_dt,y_prob=y_prob_dt)

Model          : Decision Tree
Accuracy       : 0.5987721836079455
Precision      : 0.9567081270377974
Recall         : 0.5979245283018868
F1 Score       : 0.7359156564952859
ROC-AUC        : 0.626149274664974
Test Samples   : 28343

Confusion Matrix
[[ 1126   717]
 [10655 15845]]

Classification Report

              precision    recall  f1-score       support
False          0.095578  0.610960  0.165297   1843.000000
True           0.956708  0.597925  0.735916  26500.000000
accuracy       0.598772  0.598772  0.598772      0.598772
macro avg      0.526143  0.604442  0.450606  28343.000000
weighted avg   0.900713  0.598772  0.698811  28343.000000

In [316]:
random_forest=RandomForestClassifier(n_estimators=100,class_weight='balanced',max_depth=10,max_features='sqrt',bootstrap=True,criterion='gini',random_state=42)

In [317]:
random_forest.fit(X_train_processed,y_train.values.ravel())

RandomForestClassifier(class_weight='balanced', max_depth=10, random_state=42)

In [318]:
y_pred_rf=random_forest.predict(X_test_processed)

In [319]:
y_prob_rf=random_forest.predict_proba(X_test_processed)[:,1]

In [320]:
evaluate_model('Random Forest',y_true=y_test.values.ravel(),y_pred=y_pred_rf,y_prob=y_prob_rf)

Model          : Random Forest
Accuracy       : 0.6309494407790284
Precision      : 0.954339451620213
Recall         : 0.6356981132075472
F1 Score       : 0.7630911396992208
ROC-AUC        : 0.6473550200145374
Test Samples   : 28343

Confusion Matrix
[[ 1037   806]
 [ 9654 16846]]

Classification Report

              precision    recall  f1-score       support
False          0.096997  0.562670  0.165470   1843.000000
True           0.954339  0.635698  0.763091  26500.000000
accuracy       0.630949  0.630949  0.630949      0.630949
macro avg      0.525668  0.599184  0.464281  28343.000000
weighted avg   0.898591  0.630949  0.724231  28343.000000

# Hyperparamters Tuning

In [321]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
import optuna
from sklearn.model_selection import StratifiedKFold

In [322]:
def objective(trial):
    n_estimators=trial.suggest_int('n_estimators',50,500,step=50)
    max_depth=trial.suggest_int('max_depth',5,19,step=2)
    min_samples_split=trial.suggest_int('min_samples_split',2,20,step=1)
    min_samples_leaf=trial.suggest_int('min_samples_leaf',1,10,step=1)
    max_features=trial.suggest_categorical('max_features',['sqrt','log2',None])
    
    random_forest_tune=RandomForestClassifier(n_estimators=n_estimators,max_depth=max_depth,
                                              min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf,
                                              max_features=max_features,class_weight='balanced',
                                              bootstrap=True,criterion='gini',random_state=42,n_jobs=-1)
    
    cv_f1_score=[]
    skf=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

    for train_idx,valid_idx in skf.split(X_train_processed,y_train):
        X_fold_train=X_train_processed.iloc[train_idx]
        X_fold_valid=X_train_processed.iloc[valid_idx]
        y_fold_train=y_train.iloc[train_idx]
        y_fold_valid=y_train.iloc[valid_idx]

        random_forest_tune.fit(X_fold_train,y_fold_train.values.ravel())

        y_fold_pred=random_forest_tune.predict(X_fold_valid)

        score=f1_score(y_fold_valid,y_fold_pred)

        cv_f1_score.append(score)

    return np.mean(cv_f1_score)

In [323]:
study=optuna.create_study(direction='maximize')

study.optimize(objective,n_trials=50)

[I 2026-06-29 23:12:30,113] A new study created in memory with name: no-name-8907cd24-8b5f-4381-b364-8a5ac5457aea
[I 2026-06-29 23:13:41,188] Trial 0 finished with value: 0.7623420511590957 and parameters: {'n_estimators': 450, 'max_depth': 7, 'min_samples_split': 19, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 0.7623420511590957.
[I 2026-06-29 23:19:00,565] Trial 1 finished with value: 0.8087830551270929 and parameters: {'n_estimators': 400, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 1 with value: 0.8087830551270929.
[I 2026-06-29 23:19:29,755] Trial 2 finished with value: 0.7576383349136389 and parameters: {'n_estimators': 250, 'max_depth': 5, 'min_samples_split': 16, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.8087830551270929.
[I 2026-06-29 23:19:37,871] Trial 3 finished with value: 0.7696049174421407 and parameters: {'n_estimators': 50, 'max_depth': 9, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 1 with value: 0.8087830551270929.
[I 2026-06-29 23:19:57,254] Trial 4 finished with value: 0.7620082455927585 and parameters: {'n_estimators': 150, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 1 with value: 0.8087830551270929.
[I 2026-06-29 23:22:02,394] Trial 5 finished with value: 0.8256801923921225 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 5 with value: 0.8256801923921225.
[I 2026-06-29 23:22:09,448] Trial 6 finished with value: 0.782225729513871 and parameters: {'n_estimators': 50, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.8256801923921225.
[I 2026-06-29 23:22:22,802] Trial 7 finished with value: 0.7837817354621559 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.8256801923921225.
[I 2026-06-29 23:24:41,029] Trial 8 finished with value: 0.8328732603523598 and parameters: {'n_estimators': 300, 'max_depth': 17, 'min_samples_split': 20, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 8 with value: 0.8328732603523598.
[I 2026-06-29 23:25:20,981] Trial 9 finished with value: 0.7568090202842247 and parameters: {'n_estimators': 450, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 8 with value: 0.8328732603523598.
[I 2026-06-29 23:27:24,975] Trial 10 finished with value: 0.8432687164277907 and parameters: {'n_estimators': 300, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 10 with value: 0.8432687164277907.
[I 2026-06-29 23:29:31,575] Trial 11 finished with value: 0.8432687164277907 and parameters: {'n_estimators': 300, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 10 with value: 0.8432687164277907.
[I 2026-06-29 23:31:58,019] Trial 12 finished with value: 0.8432433762116549 and parameters: {'n_estimators': 350, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 10 with value: 0.8432687164277907.
[I 2026-06-29 23:33:15,712] Trial 13 finished with value: 0.8401193810065047 and parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 10 with value: 0.8432687164277907.
[I 2026-06-29 23:35:45,526] Trial 14 finished with value: 0.8314848313558307 and parameters: {'n_estimators': 350, 'max_depth': 17, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 10 with value: 0.8432687164277907.
[I 2026-06-29 23:39:00,777] Trial 15 finished with value: 0.8312740497165111 and parameters: {'n_estimators': 500, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 10 with value: 0.8432687164277907.
[I 2026-06-29 23:41:00,539] Trial 16 finished with value: 0.8463094643985188 and parameters: {'n_estimators': 300, 'max_depth': 19, 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:42:16,026] Trial 17 finished with value: 0.8228189303440792 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:44:29,785] Trial 18 finished with value: 0.8228555204644028 and parameters: {'n_estimators': 350, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:45:03,721] Trial 19 finished with value: 0.8268428986564835 and parameters: {'n_estimators': 250, 'max_depth': 19, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:46:59,040] Trial 20 finished with value: 0.835912953303008 and parameters: {'n_estimators': 300, 'max_depth': 17, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:48:53,684] Trial 21 finished with value: 0.8432687164277907 and parameters: {'n_estimators': 300, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:51:27,889] Trial 22 finished with value: 0.8432449447374948 and parameters: {'n_estimators': 400, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:52:43,016] Trial 23 finished with value: 0.8380934134941945 and parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:54:37,138] Trial 24 finished with value: 0.8374243377241338 and parameters: {'n_estimators': 300, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:57:00,996] Trial 25 finished with value: 0.8213657305406559 and parameters: {'n_estimators': 400, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-29 23:58:34,966] Trial 26 finished with value: 0.8361303643843009 and parameters: {'n_estimators': 250, 'max_depth': 17, 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:00:46,737] Trial 27 finished with value: 0.8374256630770027 and parameters: {'n_estimators': 350, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:01:07,015] Trial 28 finished with value: 0.7994014206106822 and parameters: {'n_estimators': 150, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:02:06,290] Trial 29 finished with value: 0.8211265054395046 and parameters: {'n_estimators': 450, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:02:49,318] Trial 30 finished with value: 0.8411419772445686 and parameters: {'n_estimators': 300, 'max_depth': 19, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:04:43,952] Trial 31 finished with value: 0.8432687164277907 and parameters: {'n_estimators': 300, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:06:55,369] Trial 32 finished with value: 0.8432433762116549 and parameters: {'n_estimators': 350, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:08:26,064] Trial 33 finished with value: 0.8361303643843009 and parameters: {'n_estimators': 250, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:10:50,806] Trial 34 finished with value: 0.8460998252973904 and parameters: {'n_estimators': 400, 'max_depth': 19, 'min_samples_split': 14, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:13:43,534] Trial 35 finished with value: 0.834209744190092 and parameters: {'n_estimators': 500, 'max_depth': 17, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:15:57,793] Trial 36 finished with value: 0.8243890480250083 and parameters: {'n_estimators': 400, 'max_depth': 15, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:16:47,824] Trial 37 finished with value: 0.8360648867187729 and parameters: {'n_estimators': 400, 'max_depth': 19, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:17:17,147] Trial 38 finished with value: 0.8011555787486635 and parameters: {'n_estimators': 250, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:18:08,700] Trial 39 finished with value: 0.8354710277317565 and parameters: {'n_estimators': 150, 'max_depth': 17, 'min_samples_split': 14, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:20:50,312] Trial 40 finished with value: 0.8462519858203695 and parameters: {'n_estimators': 450, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:23:33,489] Trial 41 finished with value: 0.8462519858203695 and parameters: {'n_estimators': 450, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:26:13,644] Trial 42 finished with value: 0.8462519858203695 and parameters: {'n_estimators': 450, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 16 with value: 0.8463094643985188.
[I 2026-06-30 00:28:56,486] Trial 43 finished with value: 0.8490587304728946 and parameters: {'n_estimators': 450, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 43 with value: 0.8490587304728946.
[I 2026-06-30 00:31:32,263] Trial 44 finished with value: 0.8361078167783841 and parameters: {'n_estimators': 450, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 43 with value: 0.8490587304728946.
[I 2026-06-30 00:32:39,340] Trial 45 finished with value: 0.8393957602936423 and parameters: {'n_estimators': 500, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 43 with value: 0.8490587304728946.
[I 2026-06-30 00:33:20,766] Trial 46 finished with value: 0.7713987839587316 and parameters: {'n_estimators': 450, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 43 with value: 0.8490587304728946.
[I 2026-06-30 00:36:05,576] Trial 47 finished with value: 0.8409556569355207 and parameters: {'n_estimators': 450, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 43 with value: 0.8490587304728946.
[I 2026-06-30 00:39:13,821] Trial 48 finished with value: 0.846156187413946 and parameters: {'n_estimators': 500, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 43 with value: 0.8490587304728946.
[I 2026-06-30 00:41:58,400] Trial 49 finished with value: 0.8431578680278445 and parameters: {'n_estimators': 450, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 43 with value: 0.8490587304728946.

In [324]:
study.best_params

{'n_estimators': 450,
 'max_depth': 19,
 'min_samples_split': 2,
 'min_samples_leaf': 5,
 'max_features': None}

In [325]:
study.best_value

0.8490587304728946

In [326]:
study.best_trial

FrozenTrial(number=43, state=<TrialState.COMPLETE: 1>, values=[0.8490587304728946], datetime_start=datetime.datetime(2026, 6, 30, 0, 26, 13, 646508), datetime_complete=datetime.datetime(2026, 6, 30, 0, 28, 56, 486529), params={'n_estimators': 450, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_estimators': IntDistribution(high=500, log=False, low=50, step=50), 'max_depth': IntDistribution(high=19, log=False, low=5, step=2), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=10, log=False, low=1, step=1), 'max_features': CategoricalDistribution(choices=('sqrt', 'log2', None))}, trial_id=43, value=None)

In [327]:
def objective(trial):
    n_estimators=trial.suggest_int('n_estimators',50,500,step=50)
    max_depth=trial.suggest_int('max_depth',5,19,step=2)
    min_samples_split=trial.suggest_int('min_samples_split',2,20,step=1)
    min_samples_leaf=trial.suggest_int('min_samples_leaf',1,10,step=1)
    max_features=trial.suggest_categorical('max_features',['sqrt','log2',None])
    
    random_forest_tune=RandomForestClassifier(n_estimators=n_estimators,max_depth=max_depth,
                                              min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf,
                                              max_features=max_features,class_weight='balanced',
                                              bootstrap=True,criterion='gini',random_state=42,n_jobs=-1)
    
    skf = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
    cv_scores=cross_val_score(estimator=random_forest_tune,X=X_train_processed,y=y_train.values.ravel(),cv=skf,scoring='f1')
    return cv_scores.mean()

In [328]:
study1=optuna.create_study(direction='maximize')

study1.optimize(objective,n_trials=50)

[I 2026-06-30 00:41:58,661] A new study created in memory with name: no-name-73d7c268-50e2-4749-b146-eaf3d2e28799
[I 2026-06-30 00:44:12,360] Trial 0 finished with value: 0.7910598247553062 and parameters: {'n_estimators': 450, 'max_depth': 11, 'min_samples_split': 18, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 0 with value: 0.7910598247553062.
[I 2026-06-30 00:44:47,416] Trial 1 finished with value: 0.8402004656646158 and parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:45:07,739] Trial 2 finished with value: 0.7831409026102689 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 19, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:45:13,123] Trial 3 finished with value: 0.7816880397448079 and parameters: {'n_estimators': 50, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:45:20,827] Trial 4 finished with value: 0.8353375848989314 and parameters: {'n_estimators': 50, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:47:53,384] Trial 5 finished with value: 0.821632822494065 and parameters: {'n_estimators': 450, 'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:48:50,847] Trial 6 finished with value: 0.827226445333662 and parameters: {'n_estimators': 450, 'max_depth': 17, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:49:23,977] Trial 7 finished with value: 0.8002645383696253 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:50:08,563] Trial 8 finished with value: 0.7989868950754229 and parameters: {'n_estimators': 400, 'max_depth': 13, 'min_samples_split': 18, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:51:09,629] Trial 9 finished with value: 0.7913482443021781 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:51:37,592] Trial 10 finished with value: 0.6982414796086727 and parameters: {'n_estimators': 150, 'max_depth': 5, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': None}. Best is trial 1 with value: 0.8402004656646158.
[I 2026-06-30 00:51:44,524] Trial 11 finished with value: 0.8557742595666618 and parameters: {'n_estimators': 50, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 11 with value: 0.8557742595666618.
[I 2026-06-30 00:51:58,189] Trial 12 finished with value: 0.8574449293790115 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:52:18,649] Trial 13 finished with value: 0.8521213120939188 and parameters: {'n_estimators': 150, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:52:53,925] Trial 14 finished with value: 0.8500348348189443 and parameters: {'n_estimators': 250, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:53:01,161] Trial 15 finished with value: 0.8376175978761913 and parameters: {'n_estimators': 50, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:53:13,696] Trial 16 finished with value: 0.8155854402564142 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:53:35,551] Trial 17 finished with value: 0.7586543054440325 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:53:48,433] Trial 18 finished with value: 0.8447722119654284 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:54:06,257] Trial 19 finished with value: 0.8220636382631239 and parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:54:31,520] Trial 20 finished with value: 0.8335682546098837 and parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:54:52,150] Trial 21 finished with value: 0.8521213120939188 and parameters: {'n_estimators': 150, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:55:06,232] Trial 22 finished with value: 0.8519970923691094 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:55:13,864] Trial 23 finished with value: 0.8399723226239886 and parameters: {'n_estimators': 50, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:55:34,716] Trial 24 finished with value: 0.8504674017395553 and parameters: {'n_estimators': 150, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:56:05,713] Trial 25 finished with value: 0.8328026146273434 and parameters: {'n_estimators': 250, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:56:18,890] Trial 26 finished with value: 0.8542308791690323 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:56:27,693] Trial 27 finished with value: 0.7584364076908969 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:56:34,187] Trial 28 finished with value: 0.8173708117352472 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:56:47,286] Trial 29 finished with value: 0.8380518528569544 and parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:57:07,253] Trial 30 finished with value: 0.8550945772605762 and parameters: {'n_estimators': 50, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:57:26,502] Trial 31 finished with value: 0.8483898746244034 and parameters: {'n_estimators': 50, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:58:02,226] Trial 32 finished with value: 0.8431802199775891 and parameters: {'n_estimators': 100, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:58:21,223] Trial 33 finished with value: 0.8566863769615567 and parameters: {'n_estimators': 50, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:58:39,405] Trial 34 finished with value: 0.8433704959410167 and parameters: {'n_estimators': 50, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:58:58,360] Trial 35 finished with value: 0.851837730515238 and parameters: {'n_estimators': 50, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:59:16,435] Trial 36 finished with value: 0.8272117151002188 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 00:59:52,457] Trial 37 finished with value: 0.8489061098429254 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 01:02:51,685] Trial 38 finished with value: 0.8451804421752808 and parameters: {'n_estimators': 500, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 01:03:09,053] Trial 39 finished with value: 0.8110062350636547 and parameters: {'n_estimators': 50, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 01:03:28,849] Trial 40 finished with value: 0.7703515586787388 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 12 with value: 0.8574449293790115.
[I 2026-06-30 01:04:07,020] Trial 41 finished with value: 0.8596756563304714 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.
[I 2026-06-30 01:04:43,424] Trial 42 finished with value: 0.8590315200489268 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.
[I 2026-06-30 01:05:40,617] Trial 43 finished with value: 0.8577175795101049 and parameters: {'n_estimators': 150, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.
[I 2026-06-30 01:06:35,133] Trial 44 finished with value: 0.8449908139927096 and parameters: {'n_estimators': 150, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.
[I 2026-06-30 01:07:29,153] Trial 45 finished with value: 0.8531144767529124 and parameters: {'n_estimators': 150, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.
[I 2026-06-30 01:08:42,321] Trial 46 finished with value: 0.8456112131844133 and parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.
[I 2026-06-30 01:09:18,287] Trial 47 finished with value: 0.8543986721716752 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.
[I 2026-06-30 01:10:28,102] Trial 48 finished with value: 0.8401193810065047 and parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.
[I 2026-06-30 01:11:58,885] Trial 49 finished with value: 0.8455536629694944 and parameters: {'n_estimators': 250, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 41 with value: 0.8596756563304714.

In [329]:
study1.best_params

{'n_estimators': 100,
 'max_depth': 19,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_features': None}

In [330]:
study1.best_value

0.8596756563304714

In [331]:
study1.best_trial

FrozenTrial(number=41, state=<TrialState.COMPLETE: 1>, values=[0.8596756563304714], datetime_start=datetime.datetime(2026, 6, 30, 1, 3, 28, 851257), datetime_complete=datetime.datetime(2026, 6, 30, 1, 4, 7, 20083), params={'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_estimators': IntDistribution(high=500, log=False, low=50, step=50), 'max_depth': IntDistribution(high=19, log=False, low=5, step=2), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=10, log=False, low=1, step=1), 'max_features': CategoricalDistribution(choices=('sqrt', 'log2', None))}, trial_id=41, value=None)

In [332]:
final_random_forest=RandomForestClassifier(**study1.best_params,bootstrap=True,class_weight='balanced',criterion='gini',random_state=42,n_jobs=-1)

In [334]:
final_random_forest.fit(X_train_processed,y_train.values.ravel())

RandomForestClassifier(class_weight='balanced', max_depth=19, max_features=None,
                       min_samples_split=5, n_jobs=-1, random_state=42)

In [335]:
final_y_pred_rf=final_random_forest.predict(X_test_processed)

In [337]:
final_y_proba_rf=final_random_forest.predict_proba(X_test_processed)[:,1]

In [339]:
final_metrics_rf=evaluate_model('Random Forest',y_true=y_test.values.ravel(),y_pred=final_y_pred_rf,y_prob=final_y_proba_rf)
final_metrics_rf

Model          : Random Forest
Accuracy       : 0.7275517764527396
Precision      : 0.9339927891282241
Recall         : 0.7624905660377358
F1 Score       : 0.8395728591016745
ROC-AUC        : 0.5859722458256125
Test Samples   : 28343

Confusion Matrix
[[  415  1428]
 [ 6294 20206]]

Classification Report

              precision    recall  f1-score       support
False          0.061857  0.225176  0.097053   1843.000000
True           0.933993  0.762491  0.839573  26500.000000
accuracy       0.727552  0.727552  0.727552      0.727552
macro avg      0.497925  0.493833  0.468313  28343.000000
weighted avg   0.877282  0.727552  0.791291  28343.000000